### PR TITLE
[Javascipt/id] translating javascript guide to indonesian

### PR DESCRIPTION
**Pull request by BlinfoldKing**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by prertik** [comment]
What is the status of this?

**Comment by BlinfoldKing** [comment]
i'll continue this soon enough, sorry, but just finished my semester exam 😊

**Comment by prertik** [comment]
No worries. Do take your time. It's quality what matters.

**Comment by divayprakash** [comment]
@BlinfoldKing Any updates?

**Comment by BlinfoldKing** [comment]
@divayprakash it's done

**Comment by divayprakash** [comment]
@BlinfoldKing Could you please move the relevant commits ie. 99ac30c, 09f926e, 5f3cdbe, 747a119 and e74f618 to a new PR? The commit history for this one includes changes to a pascal doc and also a merge commit which isnt relevant to the Indonesian translation of the javascript doc.

**Pull request closed without merging**
