### PR TITLE
Update pythonstatcomp.html.markdown

### PR DESCRIPTION
**Pull request by acidflip**
- [x] PR touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Seriously, look at it now. Watch for quotes and double-check field names.

# Why?
I feel as if Statistical computing with Python was just "thrown" into the language section. Seeing as this is a tutorial and not an individual language, I believe it was just randomly thrown in with the rest of the languages which makes the site look a bit cluttered. Since there wasn't a category for tutorials, I think the best place to move this to is the "Tools" category.

### CODE REVIEW

**Comment by acidflip** [comment]
cc @adambard

**Comment by adambard** [comment]
That makes sense for now. I think I'll have to come up with some better layout one of these days and maybe sort things by language->category instead of category->language.

But, could you take your name out of the contributors? I appreciate the fix, but the page template technically assigns copyright to everyone in the contributors section, which doesn't really seem fair to the original author in this case.

**Comment by acidflip** [comment]
@adambard 

> But, could you take your name out of the contributors? I appreciate the fix, but the page template technically assigns copyright to everyone in the contributors section, which doesn't really seem fair to the original author in this case.

Done! Sorry about that, I assumed anyone who edits the page is listed as a contributor there lol.

**Comment by adambard** [comment]
Totally reasonable, we don't really have objective criteria or anything like we should. Thanks!

**Comment by acidflip** [comment]
By the way, @adambard, how often does adambard/learnxinyminutes-docs/ sync with and update the live version of the site?

**Comment by adambard** [comment]
About every 5 minutes if cron is working, and whenever I have time to check up when it's not.

**Comment by acidflip** [comment]
@adambard Oh okay, I was just asking because I noticed my merge wasn't appearing on the live site but it is now.

**Comment by adambard** [comment]
That has more than nothing to do with my having been reminded about it.

**Pull request merged**
