### PR TITLE
[hq9+] Added manual for HQ9+ programming language

### PR DESCRIPTION
**Pull request by Rogaven**
- [ \* ] PR touches only one file (or a set of logically related files with similar changes made)
- [ \* ] Content changes are aimed at _intermediate to experienced programmers_ (this is a poor format for explaining fundamental programming concepts)
- [ \* ] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ \* ] Seriously, look at it now. Watch for quotes and double-check field names.

### CODE REVIEW

**Comment by vendethiel** [comment]
@adambard should we allow golfing languages? Not sure, but then, we already have bf...

**Comment by adambard** [comment]
I think it's a bit late for us to be quibbling about notability ;p. Maybe
at sooner point I can update the home page layout to prioritize "popular"
languages, but for now I think it's fine.

**Comment by vendethiel** [comment]
Ugh, github. Thanks for not ever notifying me I had a review pending for the past 3 months...

**Comment by vendethiel** [comment]
Will fix. Thanks! :cake:

**Pull request merged**
