### PR TITLE
[multiple] Move Frameworks and Libraries to "Frameworks and Libraries" section.

### PR DESCRIPTION
**Pull request by luminist7**
In [another PR](https://github.com/adambard/learnxinyminutes-site/pull/83) I am adding support for a "Frameworks and Libraries" section.  This will help the community find docs on frameworks and libraries, and also encourage the community to document more frameworks.

In this PR, I am moving existing frameworks over to the "Frameworks and Libraries" section. Eventually, I hope many more frameworks like React, Express, Django, etc. will be created and added to Frameworks.

This is a small, but important change. I think it will really help direct the community to document more frameworks on learn x in y, which would be very helpful to developers.

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

Before:
before

After:
after

### CODE REVIEW

**Comment by vendethiel** [comment]
I don't think I've been active enough around here recently to have a say in the decision :).

**Comment by luminist7** [comment]
@adambard let me know what you think.  Also @divayprakash

**Comment by vendethiel** [comment]
This has diverged a lot with master.

**Comment by luminist7** [comment]
Resolved conflicts and updated the branch.

**Pull request merged**
