### PR TITLE
[LOLCODE/en] Create LOLCODE tutorial

### PR DESCRIPTION
**Pull request by abactel**
- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]`
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)

### CODE REVIEW

**Comment by vendethiel** [comment]
@abactel thanks for your PR! I'm not sure we should expand in that direction however?

@adambard

**Comment by adambard** [comment]
I feel like we staked out this trail when we accepted brainfuck. We should probably find a way to organize the front page a little better though -- perhaps we could use # of translations as a proxy for popularity?

**Comment by vendethiel** [comment]
Well, having them then not sorted by ne is a big confusing. I'm leaving the decision to you...

**Comment by abactel** [comment]
Perhaps a seperate subcategory for esoteric programming languages could be introduced? Doing so would allow high quality and useful content to be seperated from the not-so-useful but interesting. The only current esoteric programming language is brainfuck (and LOLCODE if this gets merged), but there's a few other interesting examples including chef (stack based language where the programs look like recepies), piet (all code is represented by a bitmap) and whitespace (uses only tabs, saces and linebreaks).

These languages don't really have any practical applications, but they explore the boundaries of computer programming design and I think ignoring them is the wrong way to go.

**Comment by vendethiel** [comment]
I'll merge this for now. Thanks.

**Pull request merged**
