### PR TITLE
[git/de] fix wording plus some typos and grammar glitches

### PR DESCRIPTION
**Pull request by cpesoft**

### CODE REVIEW

**Comment by cpesoft** [comment]
Hi @vendethiel, any probs with my PR?
The typos and grammatical errors are still there.... ;)

**Comment by vendethiel** [comment]
No, that's my bad – I thought there was another PR which fixed those.

This PR has conflicts, so you can either resolve them or I'll pull the changes in manually.

**Comment by cpesoft** [comment]
ah ok, I'll have a look then and resolve the conflicts

**Comment by cpesoft** [comment]
conflicts resolved

**Comment by vendethiel** [comment]
For some reason, github tells me this pull request is ready to be merged, but when I click on the button... It says they actually can't merge the PR :\.

**Comment by vendethiel** [comment]
ah, it says there are merge conflicts again... Sorry :(.

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
