### PR TITLE
[javascript/en][WIP] ES2015

### PR DESCRIPTION
**Pull request by excitedleigh**
This is a ⚠️ **work in progress** ⚠️ pull request for the ES2015 additions to the JavaScript document, as discussed in #1253 (as well as a bunch of other places), and based on the work in #1844, #1905 and #2491. I've still got a lot to go through, but I'm posting this up here now in case anyone wants to provide feedback.

As I go through it I'm finding that I'm rewriting a lot of the document from scratch, to ensure that each ES2015 feature appears at a logical point in the document, to match the tone and style of the rest of the text, and to make discussion of certain features either more or less brief as appropriate for LXIYM. Nonetheless, I'll add the contributors of the original PRs to the authors list before I merge this branch.

## Features to Include

- [x] Constants
- [x] Modules
- [x] Template Literals
- [ ] Classes
- [ ] Symbols (briefly)
- [ ] `for ... of`
- [ ] Default arguments in functions
- [ ] Rest/spread operator
- [ ] _More to come..._

## Features I'm Undecided On

I haven't decided whether or not it makes sense to include these features yet.

- [ ] Map and Set
- [ ] Generators
- [ ] Promises

## Features to Omit

- Iterators (I feel the iterator protocol is too nuts and bolts for an introduction like this. It'll get a mention in places like `for ... of`, but I'm not going to include the details on how to create an iterator.)

---

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by divayprakash** [comment]
@adambrenecki Any updates on this?

**Comment by divayprakash** [comment]
@thornjad Go for it!

**Comment by adambrenecki** [comment]
I no longer have my work in progress from this, and odds are I won't be
able to get to it soon, so be my guest!

**Comment by sshine** [comment]
@excitedleigh, @divayprakash: In a futile attempt to rebase it seems that javascript.html.markdown has diverged in non-trivial ways since this pull request was initiated. I believe the main value of this pull request is the overview. Implementing it would need adaptation to what's been added in the meantime.

For that reason I think it is safe to close it without disregard intended to the content.

**Comment by excitedleigh** [comment]
I agree. I also don't have time to do any further work on this (I'm leading the team running PyCon AU 2020 😱, which is nearly all my spare time gone), so it seems unfair to keep this open and thus give the impression it's actively worked on. If any of my work on this branch is of use, anyone interested is welcome to take it and improve it in a new PR :)

**Pull request closed without merging**
