### PR TITLE
asymptotic notation rough draft

### PR DESCRIPTION
**Pull request by Jakehp**
I gave this a re-read through but would definitely appreciate several more sets of eyes reading over it....

Is this clear?
Not enough explanation? Too much?
I worry this is too short to actually grasp the concept, but I think it's enough to get a basic understanding?

Once this gets cleared/merged I plan on writing up a doc on Analyzing Algorithms (big oh notation application https://github.com/adambard/learnxinyminutes-docs/issues/526#issuecomment-41224568).

### CODE REVIEW

**Comment by levibostian** [comment]
Well done @Jakehp! 

I am not quite sure how it is going to look as far as the site goes because this is a new section. The best way in my opinion to see is to merge it and see what it looks like and fix from there. So here it goes...

**Comment by Jakehp** [comment]
Welllllllp
http://learnxinyminutes.com
http://learnxinyminutes.com/docs/asymptotic-notation/

**Comment by vendethiel** [comment]
I don't think the website builder is happy with so little metadata ;-).

**Comment by Jakehp** [comment]
So what's the plan on fixing this?

**Comment by vendethiel** [comment]
waiting for @adambard .. :)

**Comment by adambard** [comment]
Right, on it.

**Comment by adambard** [comment]
Ok, so, now you can add new categories by naming them as in this PR, but you need to add a `name` field (which I've done for this article). This is the same as the `language` field in languages or the `tool` field in tools, and is clearly better, but there's no way I'm going back and changing all those over individually :P

**Comment by Jakehp** [comment]
Sounds good, thanks!

**Pull request merged**
