### PR TITLE
[coldfusion/en] Adding Coldfusion

### PR DESCRIPTION
**Pull request by wboka**
[coldfusion/en] Adding Coldfusion

### CODE REVIEW

**Comment by levibostian** [comment]
Thanks!

**Comment by wboka** [comment]
@levibostian It appears the link (http://learnxinyminutes.com/docs/coldfusion/) is returning a 404. Did I make a mistake in my file setup? I looked in a few other files and could not see anything that looked abnormal.

**Comment by levibostian** [comment]
I updated the header for the document, hopefully that fixes it. It might require a fix to the site generator as well. Lets give it a day and see what happens. If it is still 404, @adambard will have to help us out.

**Comment by wboka** [comment]
That appears to have fixed the issue. Thanks for the help.

**Pull request merged**
