### PR TITLE
[cypher/en]  Fix code blocks and rebase commits

### PR DESCRIPTION
**Pull request by TheoGauchoux**

### CODE REVIEW

**Comment by vendethiel** [comment]
This is the commit that adds the file, right?

**Comment by TheoGauchoux** [comment]
Yeah, and containing the fix. Do you prefer a rebase of the 1st (creating the file) into the 2nd commit (having the fix) ?

**Comment by vendethiel** [comment]
I just want the fix. I merged the PR that added the file already.

**Comment by TheoGauchoux** [comment]
Sorry, I will create a ultimate good PR. I apologize for this ;)

**Pull request closed without merging**
