### PR TITLE
[MANY/en] Remove Trailing Whitespace

### PR DESCRIPTION
**Pull request by Kyle-Mendes**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by divayprakash** [comment]
@adambard I'm a little conflicted about merging this PR with a single PR changing 67 files. Any thoughts?

**Comment by divayprakash** [comment]
@Kyle-Mendes Sorry for the delay in the review, I'm looking into this now.

**Comment by Kyle-Mendes** [comment]
Oh hey sorry! Didn't see this notification because I was on vacation.

I'd be happy to split it up however you wanted. I just didn't want to spam the PR tab with a bunch of PRs all doing the same thing (just trimming trailing white space) 

Just let me know and I can fix those conflicts.

**Comment by divayprakash** [comment]
@Kyle-Mendes No issues! I'm blocking a merge on this for the time being, we're currently trying to push #3856 through and your PR affects the `python` docs. I assure you we will get back to this as soon as possible. 

>I'd be happy to split it up however you wanted. I just didn't want to spam the PR tab with a bunch of PRs all doing the same thing (just trimming trailing white space)

Thanks for this, I will keep in touch with you and let you know how to proceed.

**Comment by divayprakash** [comment]
@Kyle-Mendes You can go ahead and fix the conflicts now and I'll merge this in. I imagine the python docs would need the most looking into.

**Comment by vendethiel** [comment]
This has diverged too far, sorry.

**Pull request closed without merging**
