### PR TITLE
[SASS] Add control directives, and misc. fixes

### PR DESCRIPTION
**Pull request by kaymmm**
Added a section for control directives. Added additional cases for the & selector. Added variables used in selector names. Cleaned up some inconsistent spacing and indentation.

### CODE REVIEW

**Comment by vendethiel** [comment]
Sorry for the delay. It seems this now has conflicts. If you're okay with updating the pull request, I'd be gladly to accept it :).

**Comment by kaymmm** [comment]
Pulled in all of the subsequent changes (mostly formatting) and reformatted my section for consistency (tabs>spaces).

**Comment by vendethiel** [comment]
Amazing, thanks. I can merge it now, but if you want, you can add yourself to contributors on the document & I'll merge it then.

**Comment by kaymmm** [comment]
done!

**Comment by vendethiel** [comment]
Thank you very much! 🚢

**Pull request merged**
