### PR TITLE
[jquery/tr-tr] jQuery Original Document in Turkish!

### PR DESCRIPTION
**Pull request by LeaveNhA**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

Notes:
This document is an original document, not a translation! (You guys wanted me to express this detail in the PR a few PR ago)

Thank you again, for all the effort guys!

### CODE REVIEW

**Comment by LeaveNhA** [comment]
Alive ?

**Comment by LeaveNhA** [comment]
@divayprakash alive ?

**Comment by LeaveNhA** [comment]
@Menelion, can you help me ?
This original document is stuck for six months.

**Comment by adambard** [comment]
Apologies, I'm afraid I've been a bit (a lot) behind on maintenance of this repo. Thanks very much for the contribution!

**Comment by LeaveNhA** [comment]
@adambard, you are very welcome!

I can help this community in Turkish<->English contents. 😇

**Pull request merged**
