### PR TITLE
[CloudFormation/en] Create cloudformation.html.markdown

### PR DESCRIPTION
**Pull request by PatMyron**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by PatMyron** [comment]
@adambard thoughts?

**Comment by adambard** [comment]
I'm not sure it's adding a lot of value over the CloudFormation docs as-is. Perhaps you could add some in-line comments describing the purpose and functionality of the sections and their parameters, and perhaps include some more varied examples of the resources you can configure using CloudFormation.

**Comment by PatMyron** [comment]
There are almost 500 resource types supported by CloudFormation, so I wanted to shy away from trying to strive for resource type coverage in this format. Was aiming to cover the basic structure of a template with `Parameters/Conditions/Resources` and a few examples using psuedoparameters, intrinsic functions, and resource fields like `Type/Condition/DependsOn/DeletionPolicy/UpdateReplacePolicy/Properties`

**Comment by vendethiel** [comment]
See above.

**Pull request closed without merging**
