### PR TITLE
Adds Gemfile.lock to lock charlock_holmes gem

### PR DESCRIPTION
**Pull request by Dorian**
Makes sure the tests are ran with a working charlock_holmes gem

e.g. prevents this from happening:

https://github.com/brianmario/charlock_holmes/issues/78

- [x] I solemnly swear that this is all original content of which I am the original author
-  Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by vendethiel** [comment]
What's wrong with a basic `gem install`?

**Comment by Dorian** [comment]
@vendethiel There is already a Gemfile that specify that `charlock_holmes` is needed, but the `charlock_holmes` gem doesn't work on every ruby version etc., this is a guarantee that somewhere at least someone made it work on this gem version + a ruby version (specifying a ruby version would be nice but probably a bigger change).

**Comment by samcv** [comment]
What version of ruby does not support charlock_holmes? And why are we setting the version of charlock_holmes? I don't really like that.

**Comment by Dorian** [comment]
bundler's documentation explains why a `Gemfile.lock` is important much better than me:

> This is important: the Gemfile.lock makes your application a single package of both your own code and the third-party code it ran the last time you know for sure that everything worked. Specifying exact versions of the third-party code you depend on in your Gemfile would not provide the same guarantee, because gems usually declare a range of versions for their dependencies.

http://bundler.io/v1.3/rationale.html

**Comment by samcv** [comment]
Okay, I've decided to merge this. Thanks you for answering my questions @Dorian

**Pull request merged**
