### PR TITLE
Fix for the three tutorials with broken YAML markup, causing them not to be accessible at all or show up in the index

### PR DESCRIPTION
**Pull request by samcv**
- [x] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Seriously, look at it now. Watch for quotes and double-check field names.

Fix tutorials not generating for the following reasons:
* Missing quotes
* Missing brackets
* Fullwidth commas instead of normal commas

### CODE REVIEW

**Comment by samcv** [comment]
Those three tutorials at the moment don't show up at all on learnxinyminutes.com neither in the index or directly (the URL's get a 404), this patch causes all three to build properly with middleman and show up on the site index 👍

**Comment by samcv** [comment]
Just finished rebasing it now, should be good to go.

**Comment by vendethiel** [comment]
Whoops. My bad! Thanks.

**Comment by vendethiel** [comment]
🌠

**Pull request merged**
