### PR TITLE
Fix Python typo.

### PR DESCRIPTION
**Pull request by rinoc**
Changed "Revert" to "Reverse".

### CODE REVIEW

**Comment by geoffliu** [comment]
I've been meaning to get to this one for a while now, thanks! One small request: the current wording is really misleading. The slicing actually returns a copy of the original list, but the current wording reads as if the list is reversed in place. Could you clarify a bit, while we're at it?

**Comment by rinoc** [comment]
Sure, how does this sound: "Returns a list with items in reverse order"?

**Comment by geoffliu** [comment]
"a copy of the list"? :)

**Comment by rinoc** [comment]
Alright, changed to: "Reverse a copy of the list". :smile:

**Comment by geoffliu** [comment]
Ha fine. No promise I won't change it again though. :P

**Pull request merged**
