### PR TITLE
First attempt at getting a config file for page template strings

### PR DESCRIPTION
**Pull request by geoffliu**
@adambard This is first step toward #996, you can hook up to middleman whenever you get a chance. I used YAML since Ruby has decent support of it. I don't quite know how middleman does templating, so please comment. Especially on the line about contributors, since there are multiple substitutions, and they might not always be in the same order for different languages. Being able to pass in arguments by name would be nice.

### CODE REVIEW

**Comment by geoffliu** [comment]
@adambard Gentle ping? :)

**Comment by adambard** [comment]
Right! Fixed in adambard/learnxinyminutes-site@dbf5367fe4a0a7b2accfa0b0c30a26e24979b96b. Thanks for reminding me!

**Comment by geoffliu** [comment]
Oh OK! How will people contribute to that though, being on a different (and less visible) repo?

**Comment by adambard** [comment]
I made an issue at
https://github.com/adambard/learnxinyminutes-docs/issues/1053, and also
people can just post the translations or whatever in the thread.

**Pull request closed without merging**
