### PR TITLE
[Lambda Calculus/en] - Closes #3114 - Fixes lambda calculus evaluation formula by fixing associativity

### LINKED ISSUE #3114: [Lambda Calculus] Missed associativity of parentheses
Hi,
In [Lambda Calculus Doc](https://learnxinyminutes.com/docs/lambda-calculus/) inside **Evaluation** section the formula :

- (λx.λy.λz.xyz) is equivalent to f(x, y, z) = x(y(z)) 

should be 

- (λx.λy.λz.xyz) is equivalent to f(x, y, z) = ((x y) z)

because the associativity of parentheses is left in λ-calculus.

### PR DESCRIPTION
**Pull request by chriszimmerman**
- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]`
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [X] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by chriszimmerman** [comment]
Fixes https://github.com/adambard/learnxinyminutes-docs/issues/3114

**Comment by divayprakash** [comment]
@chriszimmerman Could you also fix the same issue on line 90?

**Comment by chriszimmerman** [comment]
@divayprakash Sure thing!

**Comment by divayprakash** [comment]
@chriszimmerman Thanks for the fix!

**Pull request merged**
