### PR TITLE
Add italian language for qt

### PR DESCRIPTION
**Pull request by Ale46**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by divayprakash** [comment]
@Ale46 Could you please make this PR on a fresh branch with just your changes to [qt/it]? It's just to keep the commit history clean.

**Comment by divayprakash** [comment]
@Ale46 No not on a different lxiym branch. Your commit in your fork is not in its own branch cause the PR shows 5 commits here instead of just 1.

**Comment by divayprakash** [comment]
All your 5 pending PRs consist of all the 5 commits which should all be separate.

**Comment by Ale46** [comment]
Yep, now I see what the problem is.. That's strange, I made the changes on new branches.. Anyway I'll fix the issue and re-submit the PR.

**Pull request closed without merging**
