### PR TITLE
[Ya/en] To += PL Ya from Ya-Lang.com

### PR DESCRIPTION
**Pull request by Pavel-Senatorov**

### CODE REVIEW

**Comment by vendethiel** [comment]
Could you rebase please?

**Comment by Pavel-Senatorov** [comment]
On 2017-07-06 11:27, ven wrote:
> Could you rebase please?

Don't understand what#how to _rebase_. Please with details: I'm too new 
at GitHub.

**Comment by vendethiel** [comment]
I think it'd actually be simpler if you just saved your file, deleted your repo, re-forked, and created a new pull request

**Comment by Pavel-Senatorov** [comment]
Ok: will try to do. Yet failed to delete my pull request. Just have 
changed the title to empty. So: How to?

Is repo == pull request?

**Comment by vendethiel** [comment]
No, a pull request is for a branch. You can have many of those in a repo.

**Pull request closed without merging**
