### PR TITLE
Typos fixed in git-es.html.markdown

### PR DESCRIPTION
**Pull request by JesusTinoco**

### CODE REVIEW

**Comment by edholland** [comment]
Please squash these commits into 1

**Comment by vendethiel** [comment]
@edholland ?? We don't ask for squashing, usually.

**Comment by vendethiel** [comment]
@JesusTinoco Thank you!

**Comment by vendethiel** [comment]
:octopus:

**Comment by JesusTinoco** [comment]
@vendethiel You're welcome!

**Pull request merged**
