### PR TITLE
[unix/en] Unix terminal guide __for beginners__

### PR DESCRIPTION
**Pull request by LOZORD**
Something I started a while back. A quick beginner guide to terminal-fu for Unix and Unix-like environments.

I feel that the bash tutorial is for intermediate/advanced users. This guide aims to educate hackers who are just starting out and don't need to do any scripting yet.

Happy #hacktoberfest!

### CODE REVIEW

**Comment by levibostian** [comment]
Hmmmm...will have to ask the other collaborators on this one. I am not sure if it the best idea to have 2 files of the same language when you can just merge the beginner stuff into the original bash file. 

I get your idea with intermediate vs beginner, but this repo is also designed for people who already know how to program. People can still use the original bash file to learn. We don't want to have beginner files for all other langs to start coming up after this gets merged.

**Comment by LOZORD** [comment]
Sure, makes sense. From my experience though (as a college student), many people know how to program from basic intro courses, but honestly don't know their way around a terminal. I think this tutorial could help people, even if it does get merged into the bash one.

**Comment by vendethiel** [comment]
This should probably work as the first part of the bash tutorial

**Comment by levibostian** [comment]
Agree with both of you. You can keep the beginner stuff, just put it towards the top so beginners can ease into it.

**Comment by onebree** [comment]
If not already listed as a resource on either document:

http://cli.learncodethehardway.org/book/

**Comment by LOZORD** [comment]
I'm migrating my stuff over to the `bash` page; I will hopefully get a PR together this afternoon.
And thanks for the link @onebree, I'll add it!

**Comment by vendethiel** [comment]
@LOZORD ? :)

**Comment by LOZORD** [comment]
My apologies for the [deep freeze](https://media.giphy.com/media/WTH60K8jNd9Yc/giphy.gif)! I'll try to wrap this up after this weekend.

**Comment by vendethiel** [comment]
No rush! Thanks for working on that.

**Pull request closed without merging**
