### PR TITLE
[MongoDB/en] Add Learn MongoDB in Y Minutes

### PR DESCRIPTION
**Pull request by RogueArt**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Review by Menelion — APPROVED** [review]
Super, thank you! concise, understandable, full of resources.

**Comment by RogueArt** [comment]
@Menelion The MongoDB article doesn't show up on the website even though it's merged to master. Is there a reason why this could be happening?

Sorry for the late response, I realized I never made an issue/follow-up for this.

**Comment by Menelion** [comment]
CC @adambard. Unfortunately I have no idea about why those articles are not displayed on the site :(. Probably I need to dive deeper into the website infrastructure itself, now I'm busy with reviewing PRs, my goal is to review older open PRs as soon as possible.

**Comment by adambard** [comment]
@Menelion Thanks for the heads up! Turns out the filenames must end in `.html.markdown` exactly or the build fails, I managed to clean up the violators:

e20d8d358f9c0b1a3bf648e3a44dea3ce5dc6ce0
ccb256ebf0cd1db87d299a8ecb66ede568dc2004

This and other articles that were held up should now be all up to date. Thanks so much for all your work on this project!

**Comment by RogueArt** [comment]
That's great to hear this was resolved! Thanks for the quick response to this issue!

**Pull request merged**
