### PR TITLE
[php/en] Update php.html.markdown

### PR DESCRIPTION
**Pull request by patleeman**
- [X] PR touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [X] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [X] Seriously, look at it now. Watch for quotes and double-check field names.

Updated add item to associative array.

### CODE REVIEW

**Comment by adambard** [comment]
Doesn't that make the non-associative array example weird? It could probably be up in the associative array section.

**Comment by patleeman** [comment]
Yeah, you're right!  I was thinking of grouping it with the other action but this is a lot clearer.

**Comment by adambard** [comment]
Close, but the associative array is called `$associative` :)

**Comment by patleeman** [comment]
Boy, that's embarrassing, haha!  Thanks for your patience, it's my first pull request :smile: !

**Comment by adambard** [comment]
Looks good, thanks!

**Pull request merged**
