### PR TITLE
[php/en] type hints added in PHP 7.0

### PR DESCRIPTION
**Pull request by domnikl**
- [x] PR touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at _intermediate to experienced programmers_ (this is a poor format for explaining fundamental programming concepts)
- [x] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Seriously, look at it now. Watch for quotes and double-check field names.

### CODE REVIEW

**Comment by vendethiel** [comment]
I'm afraid that's not nearly descriptive enough. PHP 7 added the scalar part only.

**Comment by domnikl** [comment]
How about changing the comment to: "Since PHP 7.0 you can add type hints for scalar types (string, int, float) to function arguments"?

**Comment by vendethiel** [comment]
I'd rather accept a pull request that goes a bit more into detail :)

**Comment by vendethiel** [comment]
Going to close this for now. Please ping to reopen if you have time, thanks.

**Pull request closed without merging**
