### PR TITLE
[mips/en] Fixed errors

### PR DESCRIPTION
**Pull request by NightMachinary**
- [x] I solemnly swear that this is all original content of which I am the original author
- x ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Menelion** [comment]
@Spiderpig86 could you review please? Thanks.

**Review by Spiderpig86 — APPROVED** [review]
Good catch! Changes look good.

**Comment by NightMachinary** [comment]
@Spiderpig86 Can you merge this in?

**Comment by Spiderpig86** [comment]
@NightMachinary I would but I don't have write access to this repo.

**Comment by NightMachinary** [comment]
@Menelion Can you merge this in?

**Comment by Menelion** [comment]
Oh sorry guys!

**Pull request merged**
