### PR TITLE
[solidity/en] Replace constant function with view function

### PR DESCRIPTION
**Pull request by varshard**
Replace `constant` function with `view` function as `constant` keyword in functions will be deprecated soon.

- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]`
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
  - [X] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by prertik** [comment]
Hey there seems to be problem with one of your commit.

**Comment by divayprakash** [comment]
@prertik Could you please review the changes? I've updated the branch and I think it's ready for a 'squash and merge' now.

**Comment by prertik** [comment]
I cannot understand the meaning of 415ff998ba5a88672f78f20bd8098f9278dcccb5 commit. Could the commit author @varshard drop the commit?

**Comment by divayprakash** [comment]
@prertik I undid the changes made in 415ff99 in my commit d93c4a2 so that only the required changes are present ie. thode in commit 86eb5be. That is why I said a squash and merge would work here to keep repo history clean as well as close this PR.

**Comment by prertik** [comment]
Hmmm. I'll have to differ here @divayprakash, you shouldn't need to introduce a new commit to fix the wrong commit. I don't like this approach.

**Comment by divayprakash** [comment]
I do see your point @prertik. I'll cherry pick the one commit we need ie. 86eb5be and try to merge that in.

**Comment by prertik** [comment]
Yes, that will be good @divayprakash. Thanks!

**Comment by divayprakash** [comment]
Closed in favour of #3340.

**Pull request closed without merging**
