### PR TITLE
Add pt-pt translation for Scala tutorial

### PR DESCRIPTION
**Pull request by JD557**
This PR adds a Portuguese translation of the Scala tutorial.

I tested the code and it seems to be working as expected. This is my first pull request for this project though, so I might have missed something from the guidelines (eg. do I need to include the code in a separate `learn-pt.scala` file somewhere, or is it automagically generated?).

### CODE REVIEW

**Comment by adambard** [comment]
Thanks for your contribution! The code is automatically generated, but you seem to have left a duplicate `filename:` key in the header. That will guaranteed cause problems for our oh-so-fragile site generator. I recommend `learnscala-pt.scala` as the filename for consistency.

**Comment by JD557** [comment]
Oops, sorry about that.

Should be fixed now.

**Comment by vendethiel** [comment]
Hey, thanks!

**Comment by vendethiel** [comment]
:cake:

**Pull request merged**
