### PR TITLE
Multi line comment instead of single everytime [java/en]

### PR DESCRIPTION
**Pull request by vipulroxx**

### CODE REVIEW

**Comment by vipulroxx** [comment]
Anything need to be fixed?

**Comment by geoffliu** [comment]
I actually prefer using all single line comments, since it makes it clear which part is code and which part is prose. In fact, even in multiline comments, you still see `*` at the beginning of every line, for just that reason.

**Comment by vipulroxx** [comment]
ohh...I understand :)

**Comment by vipulroxx** [comment]
Could you have a look here : https://github.com/adambard/learnxinyminutes-docs/pull/1673

**Comment by vipulroxx** [comment]
Hey,
By the way I added a snippet too from 284 - 293 in this commit

**Comment by geoffliu** [comment]
@vipulroxx For languages that none of the collaborators speak, we usually leave translation PRs open for a little bit, in hopes that other people will comment on them.

For the snippet in 284-193, I'm happy to include, but please revert other changes first.

**Comment by vipulroxx** [comment]
Reverted..Please check :)

**Comment by vipulroxx** [comment]
?

**Comment by vendethiel** [comment]
I'm afraid this has merge conflicts due to the mixed changes.. Sorry for the delay :(.

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
