### PR TITLE
[funC/en-EN] added FunC intro

### PR DESCRIPTION
**Pull request by Hiyorimi**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Hello, @Hiyorimi! Thanks for your contribution 😄 Could you please check the [contribution guidelines](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)? I'll be glad to merge when the contribution is following the guidelines. One example is to try to keep line length in code blocks to 80 characters or fewer. Sometimes that's not possible, and that's fine, but it usually is such as for code comments.

**Comment by Hiyorimi** [comment]
> Hello, @Hiyorimi! Thanks for your contribution 😄 Could you please check the [contribution guidelines](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)? I'll be glad to merge when the contribution is following the guidelines. One example is to try to keep line length in code blocks to 80 characters or fewer. Sometimes that's not possible, and that's fine, but it usually is such as for code comments.

Or, thank you for replying so soon. I've reviewed the guidelines (even looked up the word 'Eschew' in a dictionary), tried and decided to keep it the way I submitted.

Will improve line length asap.

**Comment by Hiyorimi** [comment]
* [x] Keep lines under 80 chars
* [x] Prefer example to exposition
* [x] Eschew surplusage
* [x] Use UTF-8

**Comment by Hiyorimi** [comment]
Thank you!

**Pull request merged**
