### PR TITLE
[lua/zh-cn] 增加lua相关“模块”注意事项

### PR DESCRIPTION
**Pull request by dingyanhe**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by imba-tjd** [comment]
In theory you should change the en version first. Then update the translation.

**Comment by dingyanhe** [comment]
> In theory you should change the en version first. Then update the translation.

No en version

image

**Comment by imba-tjd** [comment]
https://github.com/adambard/learnxinyminutes-docs/blob/master/lua.html.markdown

**Comment by ddddyh** [comment]
> https://github.com/adambard/learnxinyminutes-docs/blob/master/lua.html.markdown

thank you.

> In theory you should change the en version first. Then update the translation.

done

**Comment by imba-tjd** [comment]
emmmm **you should open another PR changing EN version**. After EN got merged, CN can be merged.
The point is that EN is the original version, while others are translation. I have no ability to review lua syntax, I can only review translation.

**Comment by ddddyh** [comment]
> emmmm **you should open another PR changing EN version**. After EN got merged, CN can be merged. The point is that EN is the original version, while others are translation. I have no ability to review lua syntax, I can only review translation.

https://github.com/adambard/learnxinyminutes-docs/pull/4567

**Comment by verhovsky** [comment]
Mentioning LUA_PATH makes sense, but I removed the rest.

**Pull request merged**
