### PR TITLE
[javascript/ru] Translate JavaScript guide to russian

### PR DESCRIPTION
**Pull request by maximkoretskiy**

### CODE REVIEW

**Comment by adambard** [comment]
I'm just going to assume that this is as good as it's getting. Sorry to leave you in limbo so long, thanks for your contribution!

**Comment by Oire** [comment]
Uh-oh! My bad, I've absolutely forgotten we already had another PR for JS in Russian :(((. Forgive me please(

**Comment by adambard** [comment]
aw man, there were two totally different ones? Anything to be gained from comparing them?

**Comment by maximkoretskiy** [comment]
@Oire, my pull request was created 1 month earlier. What i did wrong?  Can you assess quality of my translation?

**Comment by Oire** [comment]
No, I don't think so. I've made my best in #918 :)

**Comment by Oire** [comment]
@maximkoretskiy, nothing wrong with your translation, it's just my fault. Anyway, I'll look more thoroughly and probably edit the file. Зарапортовался я, короче, не углядел, что пулл-реквестов два( Простите(

**Pull request merged**
