### PR TITLE
Create amd.html.markdown [es-es]

### PR DESCRIPTION
**Pull request by caroguerrero**

### CODE REVIEW

**Comment by vendethiel** [comment]
that's not very es-es :)

**Comment by caroguerrero** [comment]
Sorry I have not yet finished. This night ended translate the document :D

**Comment by vendethiel** [comment]
Take the time you need

**Comment by vendethiel** [comment]
@caroguerrero any news?:)

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
