### PR TITLE
[yaml/ko-KR] Translate updated en document

### LINKED ISSUE #2197: (yaml) <<: should be explained in the anchor section
[yaml/en]
Perhaps the "<<:" syntax seems familiar to some, but not to me. Is it only needed when de-referencing a complex anchor (more than just a scalar)?

### LINKED ISSUE #2558: [yaml/en] Not necessary to quote '1' to be interpreted as a number.
Near the top of the [YAML page](https://learnxinyminutes.com/docs/yaml/):

```
# If you want to use number 1 as a value, you have to enclose it in quotes, 
# otherwise, YAML parser will assume that it is a boolean value of true.
scientific_notation: 1e+12
```

However, the YAML 1.2 spec doesn't suggest this interpretation at all: http://www.yaml.org/spec/1.2/spec.html#id2803629

The YAML online parser (which uses pyyaml), [interprets `1` as an integer](https://yaml-online-parser.appspot.com/?yaml=1&type=canonical_yaml):

```

---

---
!!int "1"
```

As far as I can tell, it's not possible to create a boolean from a numeric literal [even with an explicit tag](https://yaml-online-parser.appspot.com/?yaml=!!bool+1&type=canonical_yaml):

```
!!bool 1
# produces error with pyyaml
```

### LINKED ISSUE #3098: YAML - "Like Python, sets are just maps with null values" - Wrong
In Python, sets are different objects than dicts, with different operations and semantics. They both use hashes, but that's really the only similarity.

Perhaps you're thinking of Javascript.

### LINKED ISSUE #3172: not validating
https://learnxinyminutes.com/docs/files/learnyaml.yaml does not validate in https://codebeautify.org/yaml-validator

### PR DESCRIPTION
**Pull request by justin-themedium**
This contains translations:

7d6d0311 [yaml/en] Remove unused anchor
f2b4df9a UTF-8/16/32 characters need to be encoded
699ab981 Correct wording, closes #3098
62e9ea6b Explain regexp, closes #2197
dba905ff Fix YAML, closes #3172 (#3329)
7cd43d8a [yaml/en] Use preferred style; add missing uses
ae1d18ad [yaml/en] Fix #2558 1 is interpreted as a number not as a boolean. For a boolean use we use true

Signed-off-by: Justin Yang <justin.yang@themedium.io>

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Menelion** [comment]
Thank you for your contribution! I have no knowledge in Korean and, it seems, no one of the maintainers has, so merging.

**Comment by justin-themedium** [comment]
Thank you! It's my pleasure!

When can I see the new translation in https://learnxinyminutes.com/docs/ko-kr/yaml-kr/ ?

And I would be honored if I could be a new Korean maintainer.

**Comment by Menelion** [comment]
Those are questions to our big boss @adambard again 😊

**Comment by adambard** [comment]
@justin-themedium I've added you as a collaborator, we would be most grateful for whatever maintenance you can offer! Also, I gave the cron job some encouragement, and your updated translation is now live :)

**Comment by justin-themedium** [comment]
@adambard Thank you! I've just looked at that! I'll do my best!

**Comment by justin-themedium** [comment]
Thank you! I will do my best!

B&R,
Justin


2021년 12월 10일 (금) 오전 6:59, Andre Polykanine ***@***.***>님이 작성:

**Pull request merged**
