### PR TITLE
[swift/en,cn,ru]Updating the getting started guide weblink.

### PR DESCRIPTION
**Pull request by TheDmitry**

### CODE REVIEW

**Comment by geoffliu** [comment]
Could update the file in pt-br as well? Thanks!

**Comment by TheDmitry** [comment]
Commited.
But pt-br is not visible on the LearnXinYMinutes homepage. Is it broken?

**Comment by geoffliu** [comment]
Looks like there's an extra comma in there. I'll fix it.

**Comment by geoffliu** [comment]
Oh the pt-br version has an extra comma in there, so the header section isn't parsing. I'll fix it. Thanks!

**Pull request merged**
