### PR TITLE
[fr] Improved translation in french of multiple articles

### PR DESCRIPTION
**Pull request by napnac**
I improved some of the translation in french for brainfuck, coffeescript, erlang, go, json, markdown and ruby.

Hope this will help ! :)

### CODE REVIEW

**Comment by aloisdg** [comment]
@napnac Can you write a separate PR for each file where each feature is in its own branch?

**Comment by napnac** [comment]
Hi @aloisdg !

I actually updated the repo so now you can merge this PR, it was easier than creating a separate PR for each file with different branches.

I hope this is fine for you.

**Comment by vendethiel** [comment]
I'm sorry, but the "contributors" tag is reserved for significant contributors, I'm afraid.

**Comment by aloisdg** [comment]
@napnac I am not a collaborator. I cant merge any code. I ask you to split your modifications because it would be easiest to comment for a future merge.

@vendethiel Why did you close this issue?

**Pull request closed without merging**
