### PR TITLE
[python3/en] Added examples of multiple parameters to higher order functions

### PR DESCRIPTION
**Pull request by kdelwat**
Added examples of map() and lambda functions when used with multiple variables, to increase clarity around this use case.

### CODE REVIEW

**Comment by levibostian** [comment]
Could you please do this to the python document too, please?

**Comment by kdelwat** [comment]
Well, I really stuffed that up. I'm not sure how to delete the pull request, so any help would be very appreciated!

**Comment by levibostian** [comment]
Hmmm...Did you try and merge in master? 

Doing a rebase might solve the problem. Don't close the pull request, just fix your branch and this pull request will change along with it. So merge master/rebase and push the changes up and it will all be good here and we can merge it.

**Comment by kdelwat** [comment]
All fixed now, sorry about that mess!

**Comment by levibostian** [comment]
Thanks!

**Pull request merged**
