### PR TITLE
[fsharp/en] correct a few simple mistakes

### PR DESCRIPTION
**Pull request by sholland1**
change github flavored markdown programming language to fsharp
correct typos

### CODE REVIEW

**Comment by vendethiel** [comment]
I'm not sure our parser supports fsharp...

**Comment by sholland1** [comment]
F# was heavily influenced by OCaml, and it looks the [OCaml](http://learnxinyminutes.com/docs/ocaml/) page is being parsed correctly. I can change it to use that if the parser doesn't support F#.

**Comment by sholland1** [comment]
Ok, so I did some digging, and I am guessing the parser you guys are using is [Rouge](https://github.com/jneen/rouge), since it used by the Middleman extension [middleman-syntax](https://github.com/middleman/middleman-syntax).

It appears that there is currently no support for F# in Rouge.

I also found an [online syntax highlighter](http://rouge.jneen.net/) that uses Rouge and pasted the F# code that we have into it. I tried using the OCaml and SML highlighting modes, but because neither of these languages have `//single line comments`, the highlighting for those comments was wrong.

I will change the language back to C#.

**Comment by vendethiel** [comment]
Right. Thanks :)

**Pull request merged**
