### PR TITLE
Add file to download and correct the language used in Markdown code block

### PR DESCRIPTION
**Pull request by marcelgsantos**

### CODE REVIEW

**Comment by vendethiel** [comment]
Did you check elm was supported by our highlighter?

**Comment by marcelgsantos** [comment]
I tried to check but I found nothing about this. Do you think is better to remove this change from this PR?

**Comment by vendethiel** [comment]
I'm afraid [elm is not supported](https://github.com/adambard/rouge/tree/master/lib/rouge/lexers)

**Comment by marcelgsantos** [comment]
That is a bad news! :( I will correct this and update this PR.

**Comment by marcelgsantos** [comment]
Hey @vendethiel, I made the change. Check if it is ok, please! ;)

**Comment by vendethiel** [comment]
Thanks!

**Pull request merged**
