### PR TITLE
[mysql/en] Basic structure.

### PR DESCRIPTION
**Pull request by ssundarraj**
[Review on Reviewable](https://reviewable.io/reviews/adambard/learnxinyminutes-docs/1052)

### CODE REVIEW

**Comment by JoaoGFarias** [comment]
We should try to agree exactly about what this article will be.

[The file](https://github.com/srirams6/learnxinyminutes-docs/blob/mysql-en/mysql.html.markdown) already seems to mix different technologies.

[As I said](https://github.com/adambard/learnxinyminutes-docs/issues/400#issuecomment-38201745), [Fundamentals of Database Systems](http://www.amazon.com/Fundamentals-Database-Systems-6th-Edition/dp/0136086209) is a good source on SQL. I believe this page will be of greater value if we stick to pure SQL (the language), not DBMS's.

**Comment by levibostian** [comment]
I agree with @JoaoGFarias where we should talk about SQL and not DBMS's as there are so many of them out there. Although, MySQL is so popular, why not make a document for it? What is wrong with making a MySQL doc, a PostgreSQL doc, a SQL doc, etc? I can see the docs being great reference documents.

**Comment by aloisdg** [comment]
We can start with a SQL one and add DBMS after. Each "child" of SQL should link to the pure SQL one.

I can create a [TSQL](http://en.wikipedia.org/wiki/Transact-SQL) one if needed

**Comment by categulario** [comment]
What is the next step? I would love to have a mysql/SQL LXIYM. How can I contribute to get this done?

**Comment by aloisdg** [comment]
@adambard Why did you close this?

**Comment by vendethiel** [comment]
it's been a year and a half. I'm going to keep this closed, unless @ssundarraj wants to work on it :)

**Comment by aloisdg** [comment]
@vendethiel A new issue for a new document? 😄

**Comment by ssundarraj** [comment]
@vendethiel Sorry about that. Started it off and didn't have time afterwards. If I get some time to give it a stab sometime later, I'll reopen this. Thanks :)

**Comment by vendethiel** [comment]
No problem! Thanks for your work.

**Pull request closed without merging**
