### PR TITLE
Update python3.html.markdown

### PR DESCRIPTION
**Pull request by morenoh149**
remove unneeded commented import

### CODE REVIEW

**Comment by vendethiel** [comment]
Why is that explanation unneeded?

**Comment by morenoh149** [comment]
@vendethiel that module is neither from the stdlib nor is it defined within the page itself. So I can only assume it's an artifact from some previous example.

**Comment by vendethiel** [comment]
It's just a syntax example.

**Comment by morenoh149** [comment]
then it needs a comment explaining what's going on because I didn't get it. Moreover, if one tries to execute section 6, those imports will throw errors. They should be in a big comment block.

**Comment by vendethiel** [comment]
those are fine

**Comment by vendethiel** [comment]
I mean -- I'd accept a PR with more explanation. Not less.

**Comment by morenoh149** [comment]
@vendethiel also note that function importing is already covered on line 621
```
# You can get specific functions from a module
from math import ceil, floor
print(ceil(3.7))   # => 4.0
print(floor(3.7))  # => 3.0
```

**Pull request closed without merging**
