### PR TITLE
[mercury/en] Added Mercury

### PR DESCRIPTION
**Pull request by jrfondren**
- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]`
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [X] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by divayprakash** [comment]
@adambard Could you please take a look at this? The file seems fine to me, but it just throws an error when visiting ```/docs/mercury/```. The article title shows up on the homepage but even during the build ```fatal: no such path 'mercury.html.markdown' in HEAD
``` error is thrown. The browser error when visiting ```/docs/mercury/``` is -

```
Internal Server Error
Invalid argument @ io_writev - <STDERR>
WEBrick/1.4.2 (Ruby/2.5.5/2019-03-15) OpenSSL/1.1.1b at 192.168.43.67:4567
```

**Comment by adambard** [comment]
@divayprakash I expect this is caused by the instruction to syntax-highlight for mercury (the  ```` ```mercury````) -- missing lexers like this will cause the page not to build.

Generally the workaround for this is to either a) pick a language for highlighting with similar-enough syntax that the highlighting generally works, b) dispense with the language specifier and have no highlighting, or c) develop a pygments highlighter for this language.

@jrfondren Do you have any input as to which of these would be most appropriate? Mercury's syntax doesn't look especially familiar to me, but perhaps there's some language with a pygments parser we could try? Failing that, perhaps we could just see what happens with a matlab parser (which I mention only as the one other language with % comments I can think of)

**Comment by jrfondren** [comment]
@adambard the 'prolog' syntax is probably close enough, but if a syntax in pygments is what's needed, I don't mind trying to get Mercury into pygments first. IIRC pygments uses a bunch of regexes to highlight code, which is also what vim does, and the Mercury devs supply a vim plugin.

**Comment by jrfondren** [comment]
after spending some time on this... the prolog pygment highlights Mercury just fine :)

**Pull request merged**
