### PR TITLE
[Fortran/en] [Fortran/zh-cn] Format the code, introduce the latest standard Fortran 2023

### PR DESCRIPTION
**Pull request by zoziha**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [ ] Pull request touches only one file (or a set of logically related files with similar changes made)
  - [x] two files: **Fortran/en, Fortran/zh-cn**. 
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

## What's New

1. Format the Fortran code, **improve readability**;
2. Introduce the latest standard **Fortran 2023**;
3. Remove the **minor Fortran 2015** standard, it is not a one time major standard, just a minor update;
4. Fortran 1995\~**2008** is currently the main community use standard, Fortran 2003\~2008 contains object-oriented programming (OOP) features;
5. Remove the word f90 or f95 from the filename, fortran90.html.markdown → **fortran.html.markdown**;
6. Update **Chinese(zh-cn)** version (my native language).

### CODE REVIEW

**Comment by imba-tjd** [comment]
zh is 🆗

**Review by vendethiel — APPROVED** [review]

**Comment by vendethiel** [comment]
Thanks!

**Comment by nbehrnd** [comment]
@ven  Suggestion: can then this PR filed by Nov 4, 2022

https://github.com/adambard/learnxinyminutes-docs/pull/4531

introducing `do concurrent` equally be considered for a merge?

**Comment by vendethiel** [comment]
Sorry, I need to go through the backlog of PRs still (around 150), but I also try to not keep things pile up even more…

**Pull request merged**
