### PR TITLE
translate edn to spanish

### PR DESCRIPTION
**Pull request by ginoamaury**
hello , i translate edn to spanish, 
Any questions I am willing to solve

### CODE REVIEW

**Comment by vendethiel** [comment]
It seems there are a few too many files in this PR. Could you please only send one?

**Comment by ginoamaury** [comment]
man i cant delete the change in the others files i just translate edn to spanish

**Comment by ginoamaury** [comment]
the others file... aceppted

**Comment by vendethiel** [comment]
Ok, thanks.

**Comment by vendethiel** [comment]
Thanks! sorry for the delay

**Pull request merged**
