### PR TITLE
[docker/en] Rewriting the docs for Docker

### PR DESCRIPTION
**Pull request by akshitadixit**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Great work, @akshitadixit ! 🥳 

What else do you have in mind for this article? Writing more about `docker compose`?

I think it would be interesting to mention (a) `docker logs`, (b) Dockerfiles / `docker build`, (c) and how to push an image to a container registry, among other things, before getting into more advanced topics such as `docker compose`, for example.

What do you think?

**Comment by akshitadixit** [comment]
Thank you :)

> I think it would be interesting to mention (a) docker logs, (b) Dockerfiles / docker build, (c) and how to push an image to a container registry, among other things, before getting into more advanced topics such as docker compose, for example.

Yes I agree with you, will be adding these and push the commits.

**Comment by mribeirodantas** [comment]
Hello, @akshitadixit. If you prefer, I would suggest you remove the `docker compose` part, give me a 👍, then I merge this PR, and later we can keep working on expanding/improving this article in a new PR. What do you think?

**Comment by akshitadixit** [comment]
Hi @mribeirodantas  I think I'm almost done with all the required changes, can I have like just another day to make final edits?

**Comment by mribeirodantas** [comment]
Oh, sure. No pressure at all 😄 Sorry if I made it look different. Thanks! 🥳

**Comment by akshitadixit** [comment]
@mribeirodantas apologies for the delay, this PR should be ready for review now :)

**Comment by mribeirodantas** [comment]
Amazing! Thanks for the contributions, @akshitadixit! I will merge it now 🥳

**Pull request merged**
