### PR TITLE
change python*.html.markdown add start luna-lang.

### PR DESCRIPTION
**Pull request by nagexiucai**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [ ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by adambard** [comment]
I saw your comment on luna/luna-book#17 -- I'm sure we can find a way to get pictures in. Will you need different pictures for each language?

**Comment by nagexiucai** [comment]
Yep, at least luna-lang now. Other languages, text is enough. But compatibility in consideration is better.
So, i suggest new directory, however, i am afraid of pictures/images will grow bigger. If so, we must give a limit.
Does owner have any better idea?

**Comment by adambard** [comment]
Sorry, I meant: will different *human* languages need different pictures?

I'm not sure where best to put pictures--normally I would put them in the learnxinyminutes-site repo, but if they're intrinsic to the language (and might need updating by contributors to this repo later) they're probably better here.

**Comment by nagexiucai** [comment]
:) Get it. for luna-lang i vote for here, cause pictures are intrinsic for its visual representation. So could i add pictures into learnxinyminutes-docs/images/luna and the Chinese version into learnxinyminutes-docs/zh-cn/images/luna?

**Comment by adambard** [comment]
Whoops, sorry, lost track of this one -- if you send me a pr/link to your fork with the images present where you suggested I'll see if I can't make that work!

**Comment by divayprakash** [comment]
@nagexiucai No issues, do take your time with this. It's quality that matters.

I'm closing this PR for now, please make a fresh one adding the luna-lang doc anytime you can.

**Pull request closed without merging**
