### PR TITLE
Added document about Qt framework

### PR DESCRIPTION
**Pull request by vortexxx192**
Don't know in which format code to download should be added so I put it in a separate file.
Please share your thoughts. Thank you.

### CODE REVIEW

**Comment by adambard** [comment]
Thanks for the contrib!

The code file is generated from all the code blocks in the markdown file concatenated together. Do you think that will cause problems with your file?

**Comment by vortexxx192** [comment]
Oh, I have just made the work that is automated -- my code file is an exact concatenation of all code blocks from markdown file.

**Comment by vortexxx192** [comment]
So should I now make one more commit with qt.cpp removed?

**Comment by vendethiel** [comment]
please embed the `qt.cpp` file :).

**Comment by vendethiel** [comment]
@vortexxx192 ? :)

**Comment by vortexxx192** [comment]
@vendethiel Oh sorry, missed your previous comment.

Well now I have made one more commit, is everything OK now? To be fair, I just don't get what "please embed the qt.cpp file" exactly means.

**Comment by vendethiel** [comment]
LGTM! Thank you.

**Pull request merged**
