### PR TITLE
[python/en] Improve bool examples

### PR DESCRIPTION
**Pull request by smith558**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Could you please clarify why you think this change improves the boolean examples?

**Comment by bowmanjd** [comment]
I was wondering the same thing. While using greater than does demonstrate the numerical nature of True and False in comparisons, so do the comparisons that were already there. So it doesn't feel like this change adds anything new.

**Comment by smith558** [comment]
Simply using "greater than" demonstrates the numerical nature of True and False much better. Variety over uniformity is always preffered in teaching. See clear benefit from such a simple change and no detriment. Otherwise, having so many "equality" examples next to each other seems even redundant.

**Comment by smith558** [comment]
Additionally, there's already the very same example (the one I proposed to replace) in the boolean equality section so it is indeed redundant.

**Comment by mribeirodantas** [comment]
So what's your point? We should close this PR or merge it? 😅

**Comment by smith558** [comment]
> So what's your point? We should close this PR or merge it? sweat_smile

Clearly to merge it. 🙂 I provided multiple arguments for that, and even a personal anecdote.

**Comment by mribeirodantas** [comment]
Done! 😄 Thanks for the contribution.

**Pull request merged**
