### PR TITLE
[c++/en] Fix typos and formatting, clarify the documentation in places

### PR DESCRIPTION
**Pull request by connorwaters**

### CODE REVIEW

**Comment by vendethiel** [comment]
Why remove all the backticks?

**Comment by vendethiel** [comment]
(LGTM outside from that)

**Comment by connorwaters** [comment]
Some of the remarks used backticks around keywords and identifiers while others didn't; I figured it should be consistent, and since the remarks are all comments in a source code block, the backticks don't add any formatting, so I thought it best to remove them.

**Comment by vendethiel** [comment]
Fair enough :-). Thanks!

**Comment by vendethiel** [comment]
:ship:

**Comment by vendethiel** [comment]
:shipit:

**Pull request merged**
