### PR TITLE
Add ES6 stuff to JavaScript file

### PR DESCRIPTION
**Pull request by techdavid**
See #1253

### CODE REVIEW

**Comment by adambrenecki** [comment]
This looks good, but IMO it might be helpful to put a sentence about ES6 in the preamble at the top, so people know what "ES6" means; it could also link to things like Babel.

Also, just an idea: what if each ES6 feature had something easily scannable at the beginning of its leading comment, e.g.:

```js
// [ES6 only] You can specify a default argument to use if one isn't passed in.
```

**Comment by tech4david** [comment]
> what if each ES6 feature had something easily scannable

You can <kbd>ctrl</kbd><kbd>f</kbd> "ES6 environments" but I suppose I could write it like that instead to make it clearer at a glance. And yeah, I guess I should add something to the introduction about it

**Comment by adambard** [comment]
I don't think the world is ready to just have ES6 dropped inline into the general "Javascript" file yet. I like @adambrenecki's suggestion, or else just lumping the ES6 stuff together in one, easily-ignored pile for the benefit of those who can't use ES6 yet.

**Comment by vendethiel** [comment]
we also have another ES6-oriented PR.

**Comment by ryanplant-au** [comment]
If (when?) it's included, should it be called ES6 or ES2015? ES6 has been more popular, but ES2015 is the preferred official use, and it's what I'm seeing on book covers lately.

The ES2016/ES7 standard was published this month, on the first anniversary of ES2015/ES6. Is one year a long enough wait before adding it?

**Comment by vendethiel** [comment]
I think it should be more about browser share?

**Comment by ryanplant-au** [comment]
Well, browser share's already pretty strong. The big ES6/2015 features like rest parameters, let, const, proxy, and arrow functions are all supported by three of the big four current major browsers (Firefox, Edge, and Chrome -- only Safari lags) according to CanIUse.

**Comment by vendethiel** [comment]
Yeah, the time might be now.

**Comment by vendethiel** [comment]
Still unsure what to do with this one and #1905.

**Comment by vendethiel** [comment]
Uhhh. That closed itself automatically and now I can't reopen...

**Comment by adambard** [comment]
The source repo was deleted. Guess we're out of luck.

**Comment by techdavid** [comment]
@adambard my bad, just a sec and I'll do it again

**Comment by techdavid** [comment]
@adambard sorry bout that #2491

**Pull request closed without merging**
