### PR TITLE
fix 404 of jq page

### PR DESCRIPTION
**Pull request by xiantang**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

close: https://github.com/adambard/learnxinyminutes-docs/issues/4770

### CODE REVIEW

**Comment by xiantang** [comment]
image
local build is working now

**Comment by xiantang** [comment]
@mribeirodantas  could u review this PR?

**Comment by xiantang** [comment]
image
the reason is translator item don't have value, so it's raise error

**Comment by mribeirodantas** [comment]
Thanks, @xiantang !

**Comment by askeron** [comment]
[xiantang](https://github.com/xiantang) Thanks

**Comment by Natee9969** [comment]
> * [x]  I solemnly swear that this is all original content of which I am the original author
> * [x]  Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
> * [x]  Pull request touches only one file (or a set of logically related files with similar changes made)
> * [x]  Content changes are aimed at _intermediate to experienced programmers_ (this is a poor format for explaining fundamental programming concepts)
> * [x]  If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
>   
>   * [x]  Yes, I have double-checked quotes and field names!
> 
> close: #4770

https://github.com/adambard/learnxinyminutes-docs/pull/4773#issue-1939418956

**Pull request merged**
