### PR TITLE
[language/perl6] add much needed spacing with markdown headers

### PR DESCRIPTION
**Pull request by WildYorkies**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by vendethiel** [comment]
Amazing, thanks. This one was really too heavy.

**Comment by WildYorkies** [comment]
@vendethiel It's a great start! Still feels noisy. But I'm wondering how much of that is due to the comments not getting proper syntax highlighting. Any idea why that is?

**Comment by vendethiel** [comment]
No idea :(. @samcv set us this up, but it seems [it's not highlighted correctly on her blog either](https://cry.nu/), so I'm not holding my breath for a quickfix.

**Comment by WildYorkies** [comment]
I think I'll do another PR later that breaks some of the huge text blocks away from code and in normal markdown.

Like this block below should just be normal markdown. No reason it should be in the code. Unless I'm mistaken? I know there's a "download this source code" button. So maybe we need the explanation in the source?

```
## The categories are:
# - "prefix": before (like `!` in `!True`).
# - "postfix": after (like `++` in `$a++`).
# - "infix": in between (like `*` in `4 * 3`).
# - "circumfix": around (like `[`-`]` in `[1, 2]`).
# - "post-circumfix": around, after another term (like `{`-`}` in `%hash{'key'}`)
```

**Comment by vendethiel** [comment]
This button downloads the whole file.

**Comment by WildYorkies** [comment]
It only downloads what is inside syntax fences (from what I noticed)

**Comment by samcv** [comment]
I'm guessing it may have something to do with the CSS, why the comments show up black.

**Comment by WildYorkies** [comment]
@adambard Even if the comments could be greyed out _very slightly_ that could help with readability.

**Comment by samcv** [comment]
This is a standard comment that isn't highlighting:
```html
<span class="c-Singleline"># Variable names can contain but not end with simple quotes and dashes,</span>
```
Looks like we need c-Singleline to have css like `cm`. 
The multi-line comments on the page are lighter and are displayed properly. Here is their html
```html
<span class="cm">  Multiline comments use #` and a quoting construct.</span>
```

**Pull request merged**
