### PR TITLE
Adding NGINX

### PR DESCRIPTION
**Pull request by royalharsh**

### CODE REVIEW

**Comment by xssc** [comment]
Good start, but i think a lot should be added

**Comment by royalharsh** [comment]
ok I will add more content . :+1:

**Comment by vendethiel** [comment]
@royalharsh ?

**Comment by royalharsh** [comment]
Hi. I will add some content soon. Sorry about the delay.

**Comment by vendethiel** [comment]
no problem:)

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
