### PR TITLE
[vim/ja-jp]Add translate for vim in ja-jp

### PR DESCRIPTION
**Pull request by kato-k**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

Translated the documentation about Vim into Japanese.
The document is checked by ~two~ three native Japanese speakers.
Thank you.

### CODE REVIEW

**Comment by kato-k** [comment]
ping

Please close if you don't need this pull request

**Comment by Menelion** [comment]
I can merge with no review, since I don't speak Japanese. Is it OK, @adambard?

**Comment by adambard** [comment]
@Menelion I agree, merged! I'm sure someone will tell us if something is amiss :)

**Comment by kato-k** [comment]
Thank you very much

**Pull request merged**
