### PR TITLE
[python3/en]: fix typo

### PR DESCRIPTION
**Pull request by ebzzry**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by prertik** [comment]
You might have misinterpreted here. `foo` is generally used as a placeholder names in programming it's not a typo. They are used to denote variables, functions, commands conceptually. Using this notation for comments or concepts is good practice.

**Comment by prertik** [comment]
So, i will close this pull request. Thanks!

**Comment by ebzzry** [comment]
Yes, I understand. However, there are two issues with it:

1. It no longer becomes consistent with the other sections of the guide with regards to the usage of the `#` to provide explanation of the expression. Doing so deviates from the general convention of the guide.

2. The use of the phrase `equivalent to` is strongly misleading in those contexts, because they are not equivalent. They may be similar, but not equivalent.

**Comment by prertik** [comment]
Yeah you're right.

**Comment by prertik** [comment]
I will merge this and other pull request.
Thanks!

**Comment by ebzzry** [comment]
Great! :)

**Pull request merged**
