### PR TITLE
Added typescript-pt.html.markdown

### PR DESCRIPTION
**Pull request by gabrielgomesferraz**

### CODE REVIEW

**Comment by onebree** [comment]
I would suggest renaming the pull request, as it is misleading. Instead, you are adding a translation.

**Comment by gabrielgomesferraz** [comment]
Thanks :smile:

**Comment by gabrielgomesferraz** [comment]
I wonder if it's all right with the contribution that I made?
Pois there has not been the merge.

**Comment by vendethiel** [comment]
thanks&sorry for the delay!

**Pull request merged**
