### PR TITLE
[raku/en] Add changes regarding Perl 6 rename and more:

### PR DESCRIPTION
**Pull request by uzluisf**
- [ ] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by vendethiel** [comment]
Sorry, I missed this the first time around. Thank you.

**Comment by uzluisf** [comment]
Sure, no problem!

BTW, do you have any idea why some portion of the text in the resulting HTML isn't properly highlighted? My guess is that it probably has to do with the Pod comments not being properly identified.

**Comment by vendethiel** [comment]
I don't really know, I wouldn't be surprised if the pod higlighting was subpar.

**Comment by d-lamb** [comment]
Might there need to be a newline after the `=end comment` lines?  POD parsers for Perl 5 sometimes had that problem.  I notice that the lack of syntax highlighting starts in section 1.3, right after an `=end comment`with no newline after it.

**Comment by uzluisf** [comment]
@d-lamb I'm not sure if that's the case with Raku's [Pod](https://docs.raku.org/language/pod) but it's a possibility nonetheless.

**Pull request merged**
