### PR TITLE
Added LaTeX and brainf*ck translations to Romanian

### PR DESCRIPTION
**Pull request by petru-dimitriu**
Also a tiny little typo in the LaTeX document.

### CODE REVIEW

**Comment by adambard** [comment]
Hi there! I just changed the `language` and filename of all the brainfuck docs to bf instead of brainfuck (our audience is getting broader, apparently). Do you mind touching that up and I can merge this?

**Comment by petru-dimitriu** [comment]
There you go. :)

**Comment by adambard** [comment]
Great, thanks! We can still say brainfuck in commit notes and stuff, it's just sort of the first language on the homepage.

**Comment by petru-dimitriu** [comment]
That is fine, but frankly I dislike that name too!

**Pull request merged**
