### PR TITLE
[powershell/zh-cn] correct mistakes 勘误

### PR DESCRIPTION
**Pull request by ChuckieChen945**
- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [X] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mribeirodantas** [comment]
Please, check the checkboxes as requested in the contributing guidelines. I edited your pull request with them.

**Comment by ChuckieChen945** [comment]
OK, I've finished it. @mribeirodantas

**Comment by imba-tjd** [comment]
The en-us article has huge change in #3988. The content you modified no longer exists in that one.

The link is indeed dead. But I would recommend removing `?view=powershell-7.2`

As for the second change, I think it's for demo purpose. I don't think it needs to be changed.

**Comment by ChuckieChen945** [comment]
> The en-us article has huge change in https://github.com/adambard/learnxinyminutes-docs/pull/3988. The content you modified no longer exists in that one.
> 
> The link is indeed dead. But I would recommend removing ?view=powershell-7.2
> 
> As for the second change, I think it's for demo purpose. I don't think it needs to be changed.

I agree with your suggestion. It has been revised according to your suggestion.

**Comment by imba-tjd** [comment]
Thanks for your contribution!

**Pull request merged**
