### PR TITLE
[Lambda Calculus/fr-fr] Translation

### PR DESCRIPTION
**Pull request by yvan-sraka**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by divayprakash** [comment]
@yvan-sraka Could you please update your translation with the content that has since been added to the English version?

**Comment by divayprakash** [comment]
@yvan-sraka I'll merge this in for now but feel free to make a PR just in case you wish to update this in the future. Thanks for your contribution!

**Comment by prertik** [comment]
Hmmm.. Minor hiccup here, @divayprakash. It seems you haven't checked carefully for YAML Frontmatter's  format which has created two different topics in [https://learnxinyminutes.com/](https://learnxinyminutes.com/).

**Comment by yvan-sraka** [comment]
Fixed in https://github.com/adambard/learnxinyminutes-docs/pull/3218

**Comment by divayprakash** [comment]
@prertik Well spotted! @yvan-sraka has fixed this in #3218 so I'll merge that in now.

**Pull request merged**
