### PR TITLE
[latex/en] Added docs for bullet pointed lists

### PR DESCRIPTION
**Pull request by maithuvenkatesh**

### CODE REVIEW

**Comment by voltnor** [comment]
Nice! I second this pull request.

**Comment by maithuvenkatesh** [comment]
Thanks!

**Comment by vendethiel** [comment]
Sorry we took so long to answer, looks like there's a conflict now... Could you fix it? Thanks :)

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
