### PR TITLE
[tact/en] Learning Tact language 

### PR DESCRIPTION
**Pull request by yash0501**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [x] Yes, I have double-checked quotes and field names!
- [x] Kept lines under 80 chars

### CODE REVIEW

**Comment by yash0501** [comment]
Hi @mribeirodantas, Can you please have a look over this article and merge this PR?

**Comment by delovoyhomie** [comment]
@mribeirodantas, what's up here?

**Comment by mribeirodantas** [comment]
Hey, sorry for missing this one. I just merged https://github.com/adambard/learnxinyminutes-docs/pull/4724. Can you improve it with what you brought here in another PR?

**Comment by yash0501** [comment]
Hi @mribeirodantas, I have created a new PR for improving the document. Please have a look over it 
#4751

**Pull request closed without merging**
