### PR TITLE
[powershell/en] Add syntax highlight

### PR DESCRIPTION
**Pull request by derek-austin**
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

Only the first chunk of code was highlighted, done the rest of it.

### CODE REVIEW

**Comment by samcv** [comment]
Sounds good. Thanks!

**Comment by derek-austin** [comment]
@samcv seems that it was not so good idea :/ 

Github syntax highlight is better than https://learnxinyminutes.com one.
Take a look at https://learnxinyminutes.com/docs/powershell/  after `This is a Here-String`.
Having `"` in a sigle line breaks syntax highlight.

**Comment by derek-austin** [comment]
@samcv seems that it was not so good idea :/ 

Github syntax highlight is better than https://learnxinyminutes.com one.
Take a look at https://learnxinyminutes.com/docs/powershell/  after `This is a Here-String`.
Having `"` in a sigle line breaks syntax highlight 😞

**Comment by samcv** [comment]
@derek-austin the problem is here:
```
echo "`$aString has length of $($aString.Length)"
```
You need to get rid of the ` backtick mark. Tested it with pygments which has better highlighting than what we use now, which is rouge.

**Comment by samcv** [comment]
Should be fixed with 152fddbd9245c6380f7113eb7639fbf0d1fd1c2c

Also @adambard pygments should be fine, I checked the pages and I will make a pull request for the site repo. Should allow us to add syntax highlighting to more sites. I calculated and it supports 35%+ more of our languages we have on the site than Rouge

**Pull request merged**
