### PR TITLE
Added example of C# inline properties

### PR DESCRIPTION
**Pull request by csuich2**
This was a really cool & useful trick/feature that I found while
learning C#.

### CODE REVIEW

**Comment by vendethiel** [comment]
You probably should add a note about C#5 (or was it 6?) being required here.

**Comment by vendethiel** [comment]
@csuich2 ?

**Comment by vendethiel** [comment]
@csuich2 ?

**Comment by aloisdg** [comment]
AFAIK, it is C#6 (the current version). It is worth mentioning. It is basically a getter.

**Comment by vendethiel** [comment]
Thanks!

**Pull request merged**
