### PR TITLE
[red/en] changing the formatting of comments so that lines are always <80chars.

### PR DESCRIPTION
**Pull request by robochat**
Changing the formatting of comments so that lines are always less than 80 characters. 
In fact, I erred on the side of caution so that comments are normally only go to around 76-77 chars.

### CODE REVIEW

**Comment by samcv** [comment]
Thanks!

**Comment by vendethiel** [comment]
@samcv welcome :D

**Comment by samcv** [comment]
@vendethiel if I merge in changes, how do I get it to show up as X commited with samcv, instead of X commited with Github? I see your merges do this. Would like to make sure peoples names show up next time.

**Comment by vendethiel** [comment]
Not sure how you merged this PR?

**Comment by samcv** [comment]
On Github. How do you do yours?

**Comment by vendethiel** [comment]
image

image

image

**Comment by samcv** [comment]
👍 Thanks!

**Pull request merged**
