### PR TITLE
fixed some typos, added some clarifications

### PR DESCRIPTION
**Pull request by Ricky54326**
Added some clarifications for new users trying to learn C that wouldn't be immediately obvious.

Fixed some typos.

Removed some incorrect statements.

### CODE REVIEW

**Comment by adambard** [comment]
I know you were here first, but since I've been working backwards this seems to have gotten conflicted. Do you mind giving that a merge? Thanks, and sorry about that.

**Comment by Ricky54326** [comment]
Will do when I can!

**Comment by vendethiel** [comment]
@Ricky54326 any news?

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
