### PR TITLE
[dhall/en] Add "Learn Dhall in Y minutes"

### PR DESCRIPTION
**Pull request by Gabriel439**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

Note that while GitHub supports syntax highlighting for Dhall I assume that the syntax highlighter used for https://learnxinyminutes.com does not, so I stuck to using `haskell` as the syntax highlighter which is usually close enough

### CODE REVIEW

**Comment by Gabriel439** [comment]
Is there anything that this pull request is missing?  It's been a month without any feedback

**Comment by paulyoung** [comment]
I arrived here because I thought this already existed. Please merge :)

**Comment by Profpatsch** [comment]
bump

**Comment by adambard** [comment]
Sorry for the delay, and thanks for the contribution!

**Comment by Gabriel439** [comment]
@adambard: You're welcome! And thanks! :slightly_smiling_face:

**Comment by Profpatsch** [comment]
I might provide a German translation if I can find the time.

**Comment by Profpatsch** [comment]
I translated it to German, PR: https://github.com/adambard/learnxinyminutes-docs/pull/3600

**Pull request merged**
