### PR TITLE
aiken/en Add new language (Aiken-lang)

### PR DESCRIPTION
**Pull request by Riley-Kilgore**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by verhovsky** [comment]
I don't think cryptocurrency languages should be on the website. #4912

**Comment by KtorZ** [comment]
@verhovsky I do not intend to fight but I'd be curious to understand where you draw the line? In the ticket you just linked, it seems that "solidity" and a hypothetical "bitcoin script" would be okay candidates? 

We're not here to make the promotion of any cryptocurrency or tokens (funny enough, we were just making such a statement recently on our social media account: https://x.com/aiken_eng/status/1812418373998805171. 

Given that Aiken is nowadays the most use smart contract language on the Cardano blockchain, it feels weird to hear that it's not relevant and is dismissed as a "cryptocurrency language". We are interested about the tech and committed to providing developers with a language to articulate logic around complex distributed systems. 

In the past, I personally onboarded myself on a couple of new languages through _learn X in Y minutes_, and the Aiken core team in general thought it would be a nice idea to write one for Aiken. 

There's no token to sale nor cryptocurrency to promote here. It's, first and foremost, a programming language and toolkit for a very specific domain. 

Now, if you still want to dismiss this contribution, I (we) understand and wish you a good continuation.

**Comment by ross-spencer** [comment]
+1 

Aiken is a fascinating language that offers a different lens on software development that I've certainly learned from.

**Comment by matiwinnetou** [comment]
@verhovsky I am sure you can do better, Aiken is such a gem of a language, it's simplicity is captivating.

**Comment by KtorZ** [comment]
Let's not turned this into a source of harassment. If you wanna show support for this, I suggest adding a ❤️ to the top level message from @Riley-Kilgore or my message above.

**Comment by gufmar** [comment]
I think this projects readme needs a little fix. 
I'm happy to contribute but not sure if it will accepted from a crypto guy. Here's a preview

image

**Comment by vendethiel** [comment]
I really appreciate everyone coming out of the woodworks to bandwagon on this specific issue, but I think we've got the gist of it, thanks.

**Comment by vendethiel** [comment]
To be clear: it's not that discussion is impossible, discussion is already happening. Dogpiling is however a no-go, thank you very much.

**Pull request closed without merging**
