### PR TITLE
[vb/de] add german translation of visualbasic-es.vb

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by Konfekt** [comment]
Thank you very much and pardon the oversight regarding the file naming; I was aware of it but somehow it ended up with the local one.

**Comment by vendethiel** [comment]
Looks good to me.

**Comment by nbehrnd** [comment]
@Konfekt Thanks to your submission, today I learned (https://learnxinyminutes.com/docs/markdown/) the definition of a link with an optional label can be more compact and arguably still is pretty readable.  If you equally think so, feel free to use its implementation filed [here](https://github.com/Konfekt/learnxinyminutes-docs/pull/1).

Separate from this detail, I equally think the submission looks good to me (with a pinch of salt because so far I didn't write new Visual Basic).

**Comment by Konfekt** [comment]
Yes, of course, thank you very much. This was just due to playing it safe by copy-and-paste. I gladly use the markdown link instead of its HTML conversion.

**Comment by nbehrnd** [comment]
@brianmartinuk Your 101 about visualbasic on learnxinyminutes was translated into German.  The document prepared looks fine to me; may you -- as author of the initial form -- please equally have a look on it?

**Comment by brianmartinuk** [comment]
Hi Nbehrnd, everything looks great thank you for translating this into German. Do you have a LinkedIn we can connect on?

**Comment by Konfekt** [comment]
May I ask what is still missing?

**Comment by vendethiel** [comment]
Nothing, everything looks good to go. Thank you for your contribution!

**Pull request merged**
