### PR TITLE
[php/fr] Corrected some french mistakes

### PR DESCRIPTION
**Pull request by groovytron**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by prertik** [comment]
This request has a conflict. Please change the file name from `php.html.markdown`  to `php-fr.html.markdown`. The filename has already been changed!

**Comment by prertik** [comment]
The commit `Merge remote-tracking branch 'upstream/master` is kind of dubious.

**Comment by groovytron** [comment]
That seems strange because I changed the file name following your request and the conflict remained the same. So I tried to update my local repository with yours following [GitHub's fork syncing guide](https://help.github.com/articles/syncing-a-fork/). The merge was `fast-forwarded` without conflict.
I'll check if I can fix that or open a new pull request.

**Comment by prertik** [comment]
Actually, you didn't need to commit that.
I guess this can be merged. There is no conflict.

**Pull request merged**
