### PR TITLE
[zfs/ru] Add russian translation for ZFS doc

### PR DESCRIPTION
**Pull request by A1EF**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by vendethiel** [comment]
Hi, I have the several remarks provided by an external reviewer. Can you please look at some? I can easily believe some (most?) are inherited from the document you provided, so they'll need to be fixed there too:

```
this document invented "stripe" 
the whole Виртуальные устройства sexion probably needs to be re-done de novo
and summarise zpoolconcepts(7)
and put it after Пулы хранения and link it as "в пуле, данные страйповане между VDEVами первого уровня:" 
"ZFS датасеты" probably wants to note "транспарентное сжатие"
"Пулы хранения" example 1 "типа raidz из одном устройством для четности"
these look like freebsd examples (by device naming) 
and i think the zpool list -v output doesn't match the input data 
actually none of them do, they're all for a pool created as zpool create zroot gptid/....
the zpool set comment example should note that it's ASCII-only explicitly 
the dataset examples all use tank instead of zroot too 
global replace to match the name in the first sexion
and the mount | grep examples are also freebsd format 
L232 "# Получение всех свойств" example has initial garbage? 
(looks like |123 linenos)
"Установка значения свойства на датасете" must spec compression=zstd
gzip-9 is genuinely and actively malicious 
the first property of snapshots that needs to be mentioned is what they fucking are 
not waffling about the space taken
```

**Comment by A1EF** [comment]
@vendethiel thanks for you reply. I agree with all this remarks. But all of them relative with origin file. My PR is just translation for it. I think I must stand with original until it changed.

**Comment by vendethiel** [comment]
I merged your other PR, thanks.

**Comment by A1EF** [comment]
I adjusted my commit with new changes.

**Comment by vendethiel** [comment]
Thanks :)

**Pull request merged**
