### PR TITLE
[Python] Make Python 3 default

### PR DESCRIPTION
**Pull request by sshine**
This PR addresses the same issues as #3450 opened on 2019-01-18 and is based on the premises concluded in that PR now that Python 2 was sunset 2020-01-01 as mentioned most recently in [this comment](https://github.com/adambard/learnxinyminutes-docs/pull/3450#issuecomment-581145618).

In the attempt to [rebase the `PetitPrince/master` branch](https://github.com/sshine/learnxinyminutes-docs/commits/PetitPrince-master) it became unclear to me if the change was consistent and if the rebase had consistently forwarded the changes to all translations of #3450.

So this PR replaces #3450 which may be closed in the event that this PR is accepted.

This PR takes one liberty that may be disputed:
 - 95c8b24ebf8b8e0ed02923787a9f793bdf295200: Use `language: Python 2 (legacy)` instead of `language: python (legacy, 2.x)` to conform with #3450's choice of `language: Python` for Python 3 (being uppercased).

This PR was crafted with the intent of being regularly merged. In the event that this PR is delayed from being merged, each commit contains instructions on how to replicate each step in the renaming process.

- [x] ~I solemnly swear that this is all original content of which I am the original author~
  **This is explicitly content made by @PetitPrince, remade systematically.**
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
  **Touches on all Python-related files, but logically separated into distinct commits.**
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by divayprakash** [comment]
@adambard This is quite a big change so I'd like to get your review on this.
@mxschumacher and anyone else willing to take a look please verify also.

Additionally, as a note to all collaborators, please refrain from merging in any PRs with changes to any python2 or python3 document.

**Comment by mxschumacher** [comment]
Hey - just so I understand: We have two versions of Python documentation in various languages, this change now converts python to python-legacy and python3 to python, correct?

So the changes within the files (links, names) were made automatically?

E.g. We don't need to review every line that is marked as a change here, because the code was previously reviewed

**Comment by sshine** [comment]
@divayprakash: If it makes reviewing easier, as I noted, this PR essentially carries out the work of #3450 which was already signed off on by @adambard.

> this change now converts python to python-legacy and python3 to python, correct?

Yes.

> the changes within the files (links, names) were made automatically?

All commits contain the effect of the command in their message, except for efe00fd06e2908f547ed8d47bd818301f96c4620 which is the result of manual editing. (I went through with Google Translate and made sure the context was correct in each case where I didn't speak the language.) The command in that commit should provide confirmation that no references were forgotten.

> We don't need to review every line that is marked as a change here, because the code was previously reviewed

I would still review every line, but you could do so per-commit rather than all at once, since each commit contains somewhat homogenic changes. But the intent of this PR was previously approved, yes; wrt. #3450, here is a summary of the feedback that warrants action:

- [x] "the many translations of python and python3 articles being updated similarly so that all our links don't break." (efe00fd06e2908f547ed8d47bd818301f96c4620)
- [x] "we should now point "Python" at python 3." (this is the final conclusion after some forth-and-back that was relevant prior to Python 2's sunset.)

**Comment by sshine** [comment]
@adambard mentions keeping URLs unbroken.

Since this PR contains the rename `python3` → `python`, a redirect would also need to be established.

(The rename `python` → `pythonlegacy` doesn't require a redirect, since old links will simply point to the Python 3 page after this is merged. The implications of this were discussed in #3450, so I'm just executing on that here.)

**Comment by adambard** [comment]
Looks good to me, thanks very much for @sshine !

I'd better merge this up before the docs drift out from under it again.

**Comment by divayprakash** [comment]
>I'd better merge this up before the docs drift out from under it again.

Yeah that's what worried me. Anyhow, great that this is done now. Thanks for all the work @sshine

**Pull request merged**
