### PR TITLE
[sql/es] Translate SQL to Spanish

### PR DESCRIPTION
**Pull request by FedeHC**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mxschumacher** [comment]
Hello @FedeHC - thank you for your contribution!!

I don't speak Spanish, so I cannot review this PR. Can you please recommend a Spanish speaking developer with some SQL knowledge who could review your contribution? I tried finding somebody on Twitter, but haven't gotten any response.

**Comment by FedeHC** [comment]
@mxschumacher Hi.

I'm sorry, I don't know of anyone who knows about SQL right now. If I find someone I'll let you know.

**Comment by mxschumacher** [comment]
Hey @nihilismus - thanks for reviewing. Can I merge this PR?

**Comment by nihilismus** [comment]
> Hey @nihilismus - thanks for reviewing. Can I merge this PR?

@mxschumacher Yeah, sure.
@FedeHC a really nice translation btw ^_^

**Comment by mxschumacher** [comment]
Thanks everybody !

**Pull request merged**
