### PR TITLE
[python/tr] Turkish Translate

### PR DESCRIPTION
**Pull request by erayaydin**
Python Turkish Translation

### CODE REVIEW

**Comment by vendethiel** [comment]
Thanks! I'll leave your PR open for a bit if someone wants to review it :).

**Comment by erayaydin** [comment]
OK thank you :smile: @vendethiel

**Comment by erayaydin** [comment]
Are there any review or news ?

**Comment by vendethiel** [comment]
Apparently not, so I'll just merge this :-).

**Comment by vendethiel** [comment]
Thanks for your contribution! :yellow_heart: :blue_heart:

**Comment by erayaydin** [comment]
Thank you for merge :+1: and this awesome project :smile:

**Pull request merged**
