### PR TITLE
[cobol/en] Update cobol.html.markdown

### PR DESCRIPTION
**Pull request by yhh2021**
1. Remove unnecessary (is it true? I don't know COBOL but I guess it so) global indent.
2. Indent in line 68, 69. (line 69, 70 in the original version)
3. Minor language change in line 66. (line 66, 67 in the original version)

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by precondition** [comment]
> Remove unnecessary (is it true? I don't know COBOL but I guess it so) global indent.

Legacy versions require columns 1-6 to be blank (they are used to store the index number of the punched card.)

**Comment by verhovsky** [comment]
@precondition shouldn't there be 7 spaces when we get to the code for the indicator area then?

**Comment by vendethiel** [comment]
There's freeform modes, but historically that indent was required, and is still seen in many or maybe most programs.

**Comment by verhovsky** [comment]
@vendethiel I mean we currently have this

```cobol
      *Identification division can include other values too,
      *but they are comments only. Program-id is the only one that is mandatory.
       IDENTIFICATION DIVISION.
           PROGRAM-ID.    LEARN.
           AUTHOR.        JOHN DOE.
           DATE-WRITTEN.  05/02/2020.

```

shouldn't it be this

```cobol
      *Identification division can include other values too,
      *but they are comments only. Program-id is the only one that is mandatory.
        IDENTIFICATION DIVISION.
            PROGRAM-ID.    LEARN.
            AUTHOR.        JOHN DOE.
            DATE-WRITTEN.  05/02/2020.
```

**Comment by chloekek** [comment]
The indicator area is column 7. Area A begins on column 8. There is no need to indent the code in areas A and B by another space.

**Pull request closed without merging**
