### PR TITLE
[make/zh-cn] fix translation error for make-cn.html.markdown

### PR DESCRIPTION
**Pull request by Saafo**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by imba-tjd** [comment]
> Pull request title is prepended with [language/lang-code]

**Comment by kevinnls** [comment]
@Saafo could you please add `[make/zh-cn]` to the beginning of your PR's title? 
\
point 2 of the checklist:
> Pull request title is prepended with [language/lang-code]

**Comment by Saafo** [comment]
> @Saafo could you please add `[make/zh-cn]` to the beginning of your PR's title?
> 
> point 2 of the checklist:
> 
> > Pull request title is prepended with [language/lang-code]
> 
> @imba-tjd if you can, could you please review the changes?

Sorry I‘ve fixed it.

**Comment by kevinnls** [comment]
@mxschumacher it's been reviewed. merge?

**Pull request merged**
