### PR TITLE
[coq/en] New Coq tutorial

### PR DESCRIPTION
**Pull request by philzook58**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by philzook58** [comment]
Fulfills #3161 btw

**Comment by XVilka** [comment]
Maybe it makes sense to squash into one commit?

**Comment by philzook58** [comment]
Should be better now.

**Comment by XVilka** [comment]
@divayprakash any reason not to merge this?

**Comment by adambard** [comment]
Nope, looks good to me. Thanks!

**Comment by philzook58** [comment]
Nice! Thanks!

**Comment by divayprakash** [comment]
@adambard There is some error in the build on the server. The page builds locally without errors but is not showing up on https://learnxinyminutes.com/

**Pull request merged**
