### PR TITLE
[ruby/id-id] Added Indonesian translation for Ruby

### PR DESCRIPTION
**Pull request by ukazap**

### CODE REVIEW

**Comment by vendethiel** [comment]
Thanks! :cactus:

**Comment by ukazap** [comment]
Welcome :smile:

**Comment by ukazap** [comment]
@vendethiel um, how long would it take until it show up in the homepage?

**Comment by vendethiel** [comment]
@adambard is the metadata for this one incorrect?

**Comment by adambard** [comment]
No, my cron job has just been failing recently, seems to be up now.

**Comment by vendethiel** [comment]
Thanks!

**Comment by ukazap** [comment]
Aha, nice. Thanks guys :beers:

**Pull request merged**
