### PR TITLE
[jq/en] Add jq

### PR DESCRIPTION
**Pull request by kjkuan**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mribeirodantas** [comment]
> Thank you for your work. I would like to know why it was not merged
Good question. I just merged.

**Comment by xiantang** [comment]
[https:learnxinyminutes.com/docs/jq/](https://learnxinyminutes.com/docs/jq/) But it's 404.

**Comment by mribeirodantas** [comment]
Oh, my.. Here we go 😅

**Comment by kjkuan** [comment]
Finally! But yeah it's getting 404 ... what's missing or what did I do wrong?

**Comment by xiantang** [comment]
https://github.com/adambard/learnxinyminutes-docs/pull/4773 PR is open now

**Pull request merged**
