### PR TITLE
[CMake/zh-cn]Translation CMake

### PR DESCRIPTION
**Pull request by tx23**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by mxschumacher** [comment]
Hey can you please recommend a native speaker who could review this PR?

**Comment by kevinnls** [comment]
@imba-tjd could you review please?

**Review by imba-tjd — APPROVED** [review]
* I don't know CMake
* At a glance, I didn't see any abnormal words

**Comment by imba-tjd** [comment]
Thanks for your contribution!

**Comment by kevinnls** [comment]
someone learnt CMake? :joy:

**Comment by imba-tjd** [comment]
It's been waiting too long. And it's a translation after all. If there are errors, let the community to correct them.

**Pull request merged**
