### PR TITLE
[Tailspin/en] Add page for the Tailspin language

### PR DESCRIPTION
**Pull request by tobega**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by vendethiel** [comment]
Honestly, I think that while this might be useful as a syntax reference, it's little more for someone who hasn't already read about the language.
It's missing a lot of higher-level explanations, and from the very beginning:
- doesn't explain that `->` is the basic operator to "send" data in a pipeline
- doesn't explain what `!` means and where it can appear
- doesn't explain that `'` is special
- doesn't explain what `OUT::write` means
- doesn't explain what `$#10;` means
- doesn't explain matcher syntax (inside of `<>`, what `?()` means, what `~()` would mean)
- doesn't explain what `~/` does

I think if this it to be a learning resource, it needs at least this.

**Comment by tobega** [comment]
Thanks, good feedaback! I guess I went too far on "Prefer example to exposition"

PTAL

**Comment by vendethiel** [comment]
Thank you, that's great.

> Thanks, good feedaback!

I actually went and read a few blog posts explaining how the language works etc before it clicked.

> I guess I went too far on "Prefer example to exposition"

I think the more you deviate from what most people are used to, the more you'll have to explain bits and pieces.
Especially when your syntax is symbol-heavy, it can be different to wrap your head around.
I've learned most of the articles that are here - though I'd never pretend to actually know a tenth of them - and I've used a few languages but it can still take some time getting used totally novel syntax.

**Comment by vendethiel** [comment]
Thank you :).

**Comment by tobega** [comment]
Thanks! It seems to give a 404 on the actual site. Did I do something wrong or does it just take a while?

**Comment by vendethiel** [comment]
Ah, our pygments is way outdated

**Pull request merged**
