### PR TITLE
[dart/en-en] Updated example 9: made 'i' variable non-final

### PR DESCRIPTION
**Pull request by Hiyorimi**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Hiyorimi** [comment]
@adambard  can you take a look at this please?

**Comment by mxschumacher** [comment]
Can you please explain why your change is an improvement over the existing approach? What's wrong with using final in this case?

**Comment by Hiyorimi** [comment]
> Can you please explain why your change is an improvement over the existing approach? What's wrong with using final in this case?

It doesn't compile to JavaScript:

```
Error compiling to JavaScript:
main.dart:4:47:
Error: Can't assign to the final variable 'i'.
  for (final i = 0; i < example9Array.length; i++) {
                                              ^
Error: Compilation failed.
```

You can try that yourself at the [dartpad](https://dartpad.dev/cf1669c13818f9a5d5d5e7cc0dc4c63e)

**Comment by mxschumacher** [comment]
The code runs on dartpad. You have tried to transpile this code with [dart2js](https://dart.dev/tools/dart2js) and it failed?

**Comment by Hiyorimi** [comment]
> The code runs on dartpad. You have tried to transpile this code with [dart2js](https://dart.dev/tools/dart2js) and it failed?

In the darted I used `int i`. It fails if I change it to `final i` declaration.

**Pull request merged**
