### PR TITLE
[Swift/en] Update to Swift 5 and include omitted examples

### PR DESCRIPTION
**Pull request by Samasaur1**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Samasaur1** [comment]
If possible, I'd like someone who doesn't really use Swift to take a look at this to make sure that I didn't go into too much detail

**Comment by Samasaur1** [comment]
Actually, sorry, I was looking at this again and it's not ready yet. I'll let you know when it is.

**Comment by Samasaur1** [comment]
Okay, I think it's good now

**Comment by Samasaur1** [comment]
@divayprakash Any idea when this will be looked at?

**Comment by divayprakash** [comment]
@Samasaur1 Sorry for the late response but I was on an extended hiatus due to work issues. I'm back now so this should go through quickly now.

**Comment by divayprakash** [comment]
@Samasaur1 Thank you for the contribution and welcome to the LXIYM community!

**Comment by Samasaur1** [comment]
@divayprakash Thanks!

**Pull request merged**
