### PR TITLE
[Swift/zh-cn] update to swift 4.1

### PR DESCRIPTION
**Pull request by shuliang**
update to swift 4.1 & fix typo

### CODE REVIEW

**Comment by inkydragon** [comment]
最好照着 [pr 模板改一下](https://github.com/adambard/learnxinyminutes-docs/blob/master/PULL_REQUEST_TEMPLATE.md)，不然可能会被一直放着不合并

**Comment by shuliang** [comment]
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown) -
  - [x] Yes, I have double-checked quotes and field names!

Thx @inkydragon  for your reminder ^_^

**Comment by divayprakash** [comment]
shuliang Is this ready to be merged?

**Comment by shuliang** [comment]
@divayprakash Yes, please.

**Comment by divayprakash** [comment]
@shuliang Thank you for the contribution and welcome to the community!

**Comment by shuliang** [comment]
@divayprakash It's my pleasure, thank you!

**Pull request merged**
