### PR TITLE
[Julia/en] 1-based indexing is only the default. Also periods

### PR DESCRIPTION
**Pull request by PallHaraldsson**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Note, I did only one major change on "begin", just scan for those places. From memory this works, but not prior to 0.7, so consider if you want to merge (right away).

for e.g. a[1:3] you may want to explain more, that a[begin:begin+2] is better.

This line should go sometimes (now?!):
# The result may be different in other versions of Julia

Even with "SomeOtherVar123!" allowed with !, as it's a convention for (some) functions, but rarely done for variables(?) is it needed/wanted to highlight it?

**Comment by inkydragon** [comment]
I don't know why I've got an error. It looks like something wrong.
```
julia> arr = [1 2 3 4 5]
1×5 Array{Int64,2}:
 1  2  3  4  5

julia> arr[begin]
┌ Warning: Deprecated syntax `"begin" inside indexing expression` at REPL[9]:1.
└ @ REPL[9]:1
ERROR: syntax: unexpected "]"

julia> arr[end]
5

julia> a = [1:5;]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> a[begin+1:end]
┌ Warning: Deprecated syntax `"begin" inside indexing expression` at REPL[13]:1.
└ @ REPL[13]:1
ERROR: syntax: missing last argument in "1:" range expression

julia> a[end]
5

julia> a[begin]
┌ Warning: Deprecated syntax `"begin" inside indexing expression` at REPL[15]:1.
└ @ REPL[15]:1
ERROR: syntax: unexpected "]"
```
By the way, in v0.7 it cause the same error.

and my julia version
```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
```

**Comment by PallHaraldsson** [comment]
I recall an issue on allowing "begin" in such context, but it may not have been merged for 1.0; possibly a better way found. I found this package:

https://github.com/JuliaArrays/CustomUnitRanges.jl

https://docs.julialang.org/en/latest/devdocs/offset-arrays/

older package (redundant with the other?) is OffsetArrays.jl.

**Comment by divayprakash** [comment]
@PallHaraldsson Could you please look into the merge conflict that is occurring here?

**Comment by divayprakash** [comment]
As pointed out above, the `begin` method of accessing first element of an array does not work in either Julia v0.6.2 or v1.0.0. PR is being closed accordingly.

**Pull request closed without merging**
