### PR TITLE
[MIPS/en] pull request

### PR DESCRIPTION
**Pull request by Spiderpig86**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Spiderpig86** [comment]
@adambard small bump (great work on the project!)

**Comment by adambard** [comment]
Thanks!

**Comment by Spiderpig86** [comment]
Quick question: I believe some users have asked this before but is there CI to get the website updated?

**Comment by adambard** [comment]
There is, if you consider a cron job rebuilding the site CI -- it got briefly stuck but seems to be back in order now.

**Comment by Spiderpig86** [comment]
Thanks for the swift reply!

**Pull request merged**
