### PR TITLE
[C/zh-cn] Fix typos

### PR DESCRIPTION
**Pull request by muxueqz**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by inkydragon** [comment]
@muxueqz 改一下标题啦~ 最前面加上 `[C/zh-cn]`

**Comment by inkydragon** [comment]
可以了 (其实 pr 的模板就是流程，我提的是第二点

**Comment by divayprakash** [comment]
@muxueqz Is this ready to be merged?

**Comment by inkydragon** [comment]
@divayprakash Yes! This pr fixed a typo.

**Comment by divayprakash** [comment]
LGTM, so I'm merging this in!

**Pull request merged**
