### PR TITLE
[python/en] Add some stuff to lists, tuples, dicts, sets and classes

### PR DESCRIPTION
**Pull request by evuez**
For both Python 2 and Python 3

Python 3 only:

- Tuples: added extended unpacking
- Dictionaries: added new unpacking from Python 3.5

Both Python 2 and 3:

- Lists: added `remove`, `insert` and `index`
- Sets: added ^, <=, >= operators
- Classes: added propery decorator (including getter, setter, deleter)

### CODE REVIEW

**Comment by levibostian** [comment]
Great! Can you do the same to the python2 tutorial? (excluding the python3 specific stuff of course)

**Comment by evuez** [comment]
Yeah definitely! I'll do that by the end of the day ;)

Do you want it in another PR or do I commit on this one?

**Comment by evuez** [comment]
OK so I updated the python 2 tutorial too (in this PR).

**Comment by levibostian** [comment]
Great, thanks! Now...can you merge in master please?

**Comment by evuez** [comment]
Should be OK now :)

**Pull request merged**
