### PR TITLE
[Bash/nl-nl] fix for typo’s

### PR DESCRIPTION
**Pull request by Tapmemer**
fixes for typo’s

- [ ] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by adambard** [comment]
Thanks for the fixes! I noticed you seem to have an english-language D article in this branch. I'm not sure if this is a good joke about the Dutch and their general english fluency or not, but either way it's probably a bit redundant to put live.

**Comment by Tapmemer** [comment]
yeah i was planning to translate D to dutch too but i lack time for that

**Comment by adambard** [comment]
Great, thanks!

**Comment by Tapmemer** [comment]
No problem

**Pull request merged**
