### PR TITLE
[rust/en] Include resource for advanced Rust projects

### PR DESCRIPTION
**Pull request by sarupbanskota**
Adding CodeCrafters, which is commonly recommended as the appropriate resource for intermediate to advanced-level practice projects. Here's a [Jon Gjengset stream](https://www.youtube.com/watch?v=jf_ddGnum_4&t=200s&ab_channel=JonGjengset) doing Build your own BitTorrent.

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by sarupbanskota** [comment]
I'm happy to make a similar, single PR for all other languages, where CodeCrafters has intermediate-to-advanced projects available — lmk :)

**Comment by mribeirodantas** [comment]
Hello, @sarupbanskota ! Thanks for opening this PR. Your project looks pretty nice!

Could you clarify how does it work in terms of access? What does one need to pay for? What's free?

Best,

**Comment by mribeirodantas** [comment]
I tried the one for creating your own Docker and very quickly I ran into a pay-to-go-on alert 😅

**Comment by sarupbanskota** [comment]
In theory, 2 stages of every challenge is free, and the rest of the stages require a membership. In practice, we usually have a challenge free. e.g currently the Build your own HTTP Server challenge is completely free while it's in Beta. When we launch Build your own DNS Server (probably next week), that'll remain free for a while. The challenge [overviews](https://app.codecrafters.io/courses/bittorrent/overview), prompts, tests, [screencasts](https://app.codecrafters.io/courses/redis/stages/2/screencasts) and [concepts](https://app.codecrafters.io/collections/rust-primer) are always free.

**Comment by mribeirodantas** [comment]
Interesting. Thanks for the feedback! I think it's worth adding to this current article. It'd be cool to see what other people think about it, though (before adding to all articles). @vendethiel @adambard What do you think?

**Comment by sarupbanskota** [comment]
I forgot to mention, that if the "free" is a concern, that we'll also be launching a new initiative next week, which allows getting free CodeCrafters access by inviting your friends (you can effectively get a whole year free by inviting enough) :-)

Some HN chatter for more context:
* https://news.ycombinator.com/item?id=37941075
* https://news.ycombinator.com/item?id=32342334

**Comment by MinisculeGirraffe** [comment]
@sarupbanskota  Is the CEO of CodeCrafters and is on a marketing campaign to get their company included in as many repositories as possible. 

Out of principle I would say this should not be merged.

**Comment by vendethiel** [comment]
Yeah no. See https://github.com/rust-lang/rustlings/pull/1760#issuecomment-1806950184 for justification.

**Pull request closed without merging**
