### PR TITLE
[javascript/en]: add es6 updates to javascript. fixes #939

### LINKED ISSUE #939: [javascript] Could add some content/links about ES6
https://espadrine.github.io/New-In-A-Spec/es6/
https://6to5.org/docs/learn-es6/
https://github.com/lukehoban/es6features

### PR DESCRIPTION
**Pull request by srrvnn**
added introduction to es6. and the following concepts: 

assignment destructuring / spread / rest / arrow functions / template literals / object literals / classes / let and const / symbols / iterators / maps / sets / proxies / modules. 

added link to babeljs.io and esfiddle.net

### CODE REVIEW

**Comment by adambrenecki** [comment]
This all looks good, but I wonder if it's a bit too long - it adds a whole 40% to the length of the file!

IMO, the iterator API is way too nuts and bolts for this sort of document (although I do think `for ... of` should be in there, maybe with a 1-sentence explanation of how it's different to `for ... in`). That's a fair chunk of it. I'm in two minds how essential symbols and proxies are, too; other than that the rest is all stuff that needs to be there.

**Comment by vendethiel** [comment]
@srrvnn sorry for the delay, it seems that has merge conflicts now.

**Comment by vendethiel** [comment]
Actually... This might want to be its own article. @adambard ?

**Comment by geoffliu** [comment]
@vendethiel @adambard 

Just my $0.02:

Personally I don't think it's worth maintaining two articles, since the Javascript community has been quick to adapt to the new standard. With the myriad transpilers and polyfills out there, I see little point in keeping the old syntax around. 

I propose we add a link to the article that points to the current git commit, so if people really want, they can go find the old syntax (something like this: https://github.com/adambard/learnxinyminutes-docs/blob/6e9e1f4af018dc0e277c968d9b5fe011e0a1ce97/javascript.html.markdown). Going forward, we can update the syntax to the new ES6 standard.

**Comment by vendethiel** [comment]
Fair enough.

**Comment by vendethiel** [comment]
Still unsure what to do with this one and #1844.

**Comment by adambard** [comment]
Experienced javascript devs may be using ES6 with transpilers, but I suspect a majority of people looking for a JS syntax reference are probably going to want stuff that will work in browsers unmodified, and there's [still a lot of red](http://kangax.github.io/compat-table/es6/) in the compatibility table. I'd be ok with an ES6 addendum, but for the moment I still think limbo is the appropriate place for this PR.

**Comment by samcv** [comment]
I think either putting all the ES6 stuff at the bottom in its own section would be good as long as it's clear that it's not all supported yet in browsers.

**Comment by vendethiel** [comment]
Hey!

I think it's about time we start adding ES6 info.
There's another PR for it: #2491.
I'm not sure whichever should be picked, but if we could get them "merged" I think it'd be pretty great.
If you have some time to look at the other PR, please tell us!

**Comment by adambrenecki** [comment]
I had the same thought not long ago—most browsers support nearly all of ES6, so it's probably time to add it to the LXIYM (with explanatory notes).

My intention is to combine and edit the two existing PRs myself, but I probably won't get to that until next weekend (I've got a Uni assignment to finish and a meetup talk to prepare this weekend 😦).

**Comment by divayprakash** [comment]
Closed in favor of #2858.

**Pull request closed without merging**
