### PR TITLE
[pascal/th] Translate Pascal to Thai language

### PR DESCRIPTION
**Pull request by Jedt3D**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
    - [x] Yes, I have double-checked quotes and field names!

Sorry guys for my previous errors on previous requests. First time here.

### CODE REVIEW

**Comment by Jedt3D** [comment]
Oh.. don't know what went wrong now. 
I've tried and tested on my machine & passed.

> (base) WorajedtMBPro2019:learnxinyminutes-docs worajedt$ rake
> /Users/worajedt/.rbenv/versions/2.2.10/bin/ruby tests/encoding.rb
> Notice: ./ro-ro/clojure-ro.html.markdown was detected as ISO-8859-2 encoding. Everything is probably fine.
> Notice: ./ro-ro/ruby-ro.html.markdown was detected as ISO-8859-2 encoding. Everything is probably fine.
> Notice: ./ro-ro/coffeescript-ro.html.markdown was detected as ISO-8859-2 encoding. Everything is probably fine.
> Notice: ./id-id/bf-id.html.markdown was detected as ISO-8859-9 encoding. Everything is probably fine.
> Notice: ./id-id/markdown.html.markdown was detected as ISO-8859-9 encoding. Everything is probably fine.
> Success. All 652 files passed UTF-8 validity checks.
> /Users/worajedt/.rbenv/versions/2.2.10/bin/ruby tests/yaml.rb
> All 652 files were verified valid YAML
> (base) WorajedtMBPro2019:learnxinyminutes-docs worajedt$

**Comment by Jedt3D** [comment]
![The [IMAGE] of first 10 lines with invisible characters show.](https://uc928f5f39016bb4d75c25f152a5.previews.dropboxusercontent.com/p/thumb/AAdcf-nm3btRZGRSbJpuT7a5ejlwG6fRiy3TvUXL4YAXEXU0009W6ExvGcb-El2fzeIUO2O3Wv61kNwIlb_-PZO7-T4XMA_KQtaUUzfzNym542cka9shoTvrFzMoF0DI9Zn6F4ElRQWH7p7FIjDWxjSjIdd4Dh2QJ4YGzBE_ybQW9UB3yaklXys2RbATc-hEzYzXdC7IUVHjh-O5_KcParqQjOzLHOeVSodFXhNq5swsKelXG8s20l3kTS0i7x_BGMTVlEXp5b9eLCDch-1sLoWoui5tGMhHMeiFmEIEvIXJtmGq5Bm5VizSBpUqWNlOH3kP6VkLBWkROy0H_uaev1tF9mL2WTfY0UH2Rka4z1H_uiBB2BbSILRm46QWOhB_7WY/p.png?fv_content=true&size_mode=5)

**Comment by Jedt3D** [comment]
@adambard Would you mind to help me please.
I've no idea where to solve this weird problem. :(

**Comment by Jedt3D** [comment]
### it works!

**Comment by adambard** [comment]
Looks like you got it, thanks for your contribution!

**Pull request merged**
