### PR TITLE
[AMD/pt-br] Asynchronous Module Definition translation

### PR DESCRIPTION
**Pull request by felipest9**
I've translated the whole article about AMD.

### CODE REVIEW

**Comment by vendethiel** [comment]
Sorry, is there an issue with this? I know we tend to leave the PR open for some native speaker to comment on it, and at times we forget such PRs -- I'm sorry for that. A simple nudge should get a merge, though.

Can I reopen this and merge?

**Comment by felipest9** [comment]
@vendethiel my bad, I don't know why I press "close", this is my first contribution!

**Comment by vendethiel** [comment]
Thanks for that :)!

**Comment by vendethiel** [comment]
:star: :star2: :stars:

**Pull request merged**
