### PR TITLE
Translation fixes and extra information

### PR DESCRIPTION
**Pull request by eltonvs**

### CODE REVIEW

**Comment by vendethiel** [comment]
@JoaoGFarias?

**Comment by JoaoGFarias** [comment]
@vendethiel, @eltonvs just added some information to make the text clearer.
I did a raw translation (human-made, not an automatic); some parts are better written as @eltonvs did.

It's not a great improvement, but I'd merge it anyway.

@eltonvs, can you add this modifications to the English version?

[]s
João

**Comment by eltonvs** [comment]
@JoaoGFarias added.

**Comment by vendethiel** [comment]
Thanks!

**Pull request merged**
