### PR TITLE
[python/en] Added <> to boolean operators

### PR DESCRIPTION
**Pull request by Dor-Ron**
It's a lesser known and less common part of the language, but much like SQL <> can be used to see if 2 objects are dissimilar in Python 2.

### CODE REVIEW

**Comment by payet-s** [comment]
Be careful, this syntax is deprecated in Python2 and incorrect in Python3.
You should at least mention the deprecated aspect of this syntax alternative.

Otherwise, it's always good to know, specially when you're reading someone else code that might use it.

**Comment by Dor-Ron** [comment]
You're right, comment added!

**Comment by vendethiel** [comment]
I'm not sure we should show deprecated features.

**Comment by payet-s** [comment]
It might be good to know. Especially because this syntax is used in others languages like Pascal and it can be present in someone else code. At least, you know that it exists even if you don't use it often.

**Comment by geoffliu** [comment]
I have never seen this syntax used, and with the deprecation, it's going to be less relevant.

**Pull request closed without merging**
