### PR TITLE
Fix some misplaced comments

### PR DESCRIPTION
**Pull request by billpcs**
Some */ where missing or in the wrong place with result to code syntax highlighting not showing correctly

### CODE REVIEW

**Comment by vendethiel** [comment]
Thanks!

**Comment by vendethiel** [comment]
Actually, the 2nd change is wrong, the HTML element shouldn't appear in the middle of the CSS file.

**Comment by billpcs** [comment]
So it has to be commented out?

**Comment by vendethiel** [comment]
Yes, please. We'd like the file to stay CSS only :)

**Comment by billpcs** [comment]
So, I have to read a book about git. I have no idea how all this works. Anyway, I deleted my fork and reforked this repo. I made the changes needed. Now? I make a new pull request or what?

**Comment by vendethiel** [comment]
yes, please :-).

**Pull request merged**
