### PR TITLE
[AsymptoticNotation/PT-BR] Asymptotic Notation translation to PT-BR

### PR DESCRIPTION
**Pull request by JoaoGFarias**

### CODE REVIEW

**Comment by vendethiel** [comment]
@adambard what should be done wrt translation?

**Comment by adambard** [comment]
@vendethiel Wow, those @-tags just get totally lost in all the activity.

My default position is merge if you can't say why not, so let's do.

**Comment by vendethiel** [comment]
@adambard That's why I always first filter by "mention" on github :)

**Comment by JoaoGFarias** [comment]
Thanks guys o/

**Pull request merged**
