### PR TITLE
[bash/en] fix comparison syntax

### PR DESCRIPTION
**Pull request by matteobaglini**

### CODE REVIEW

**Comment by vendethiel** [comment]
Both are correct, AFAIK? Also, our guidelines file specify when to add yourself as a contributer

**Comment by matteobaglini** [comment]
I removed the self addition commit. Sorry for that, I had misunderstood the contribution rules.

**Comment by matteobaglini** [comment]
I tried the script while reading the guide and the `if` expression at line 86 throw an `integer expression expected` error.

According to [Advanced Bash-Scripting Guide](http://www.tldp.org/LDP/abs/html/comparison-ops.html) that error is raised because the script use integer comparison (-ne) instead of string comparison (!=).

**Comment by vendethiel** [comment]
Looks good then! Thanks :). :cake:

**Pull request merged**
