### PR TITLE
[php-composer/en] Add new tool document for Composer, PHP's dependency manager

### PR DESCRIPTION
**Pull request by Glutnix**
Feedback desired. Hope you like it!

### CODE REVIEW

**Comment by Glutnix** [comment]
So no-one wants this? What should be done with this?

**Comment by Oire** [comment]
I'll review in a couple days. @adambard, @levibostian, @vendethiel?

**Comment by vendethiel** [comment]
sorry, I'm a bit "off" these days :-). LGTM, thanks @Glutnix

**Comment by vendethiel** [comment]
@Oire ?

**Comment by adambard** [comment]
Seems good to me.

**Pull request merged**
