### PR TITLE
[cypher/en] Write tiny tutorial on Cypher

### PR DESCRIPTION
**Pull request by TheoGauchoux**

### CODE REVIEW

**Comment by vendethiel** [comment]
No idea about all this, I trust you fully :). Thanks!

**Comment by vendethiel** [comment]
:cake:

**Comment by TheoGauchoux** [comment]
Thanks! 👍

**Comment by TheoGauchoux** [comment]
According to the production version (on the .com site), the use of \`code\` characters from markdown to describe a short part of code isn't well displayed (but well displayed in the GitHub viewer).

However the code block characters (\```long code\```) is okay.

**Comment by vendethiel** [comment]
We do not use Github's markdown parser, so this might be why.

**Comment by TheoGauchoux** [comment]
Okay, I will fix my markdown to be compliant with your parser :)

**Pull request merged**
