### PR TITLE
[latex/en] Typo fixes and footnote demonstration

### PR DESCRIPTION
**Pull request by ramananbalakrishnan**
- Fixed grammar in certain section
- Corrected usage of `` and '' for proper double-quotes in latex. ( I noticed that this has been discussed earlier, but this is how LaTeX syntax works, i.e. `` for open-quotes and '' for close-quotes )
- Added a footnote example, to explain the often need for multiple compiler passes

Related
pull request : #1412
issue : #1119

### CODE REVIEW

**Comment by vendethiel** [comment]
Sorry, but we reserve "contributors" section to significant document contributors

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Comment by ramananbalakrishnan** [comment]
I made missed this previously. 

Created a new PR (https://github.com/adambard/learnxinyminutes-docs/pull/2481), with only the content edits.

**Comment by vendethiel** [comment]
Amazing! Thanks for being so quick.

**Pull request closed without merging**
