### PR TITLE
[Haxe/en] update links on haxe.html.markdown

### PR DESCRIPTION
**Pull request by uvtc**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by uvtc** [comment]
Hi. I'm a bit unfamiliar with the process here. Have I made an error with my commit? Is there something I should do to get the CI checks to pass here? Thanks.

**Comment by divayprakash** [comment]
@uvtc Please merge master with your branch. That should fix the failing Travis build. There was an issue with the tests which has since been fixed on master.

**Comment by uvtc** [comment]
Thanks very much, @divayprakash !

**Comment by divayprakash** [comment]
@uvtc Thanks for the contribution!

**Pull request merged**
