### PR TITLE
[python/ru] Fixing Russian translation for Python

### PR DESCRIPTION
**Pull request by Oire**
I've updated the Russian translation of both Python tutorials to reflect changes in English files.

### CODE REVIEW

**Comment by Oire** [comment]
@adambard, I don't actually know why but the commit history is messed up :(. I created a new branch, pushed one single commit and made a PR but it shows what it shows. What should I do to resolve this, please? Thanks!

**Comment by Oire** [comment]
@adambard, @levibostian, @vendethiel, so could anyone suggest me what to do, please? Could that be merged?) Thanks!

**Comment by vendethiel** [comment]
what was the last commit merged in this history?

**Comment by Oire** [comment]
@vendethiel, actually, I don't know what happens :(. I branched rom my `master`, fixed two files (both Python tutorials in Russian), pushed in, created a pull request and... got this mess :(. Basically, there should be one and single commit in the `fix-python-ru` branch. So should I rebase it somehow?

**Comment by Oire** [comment]
@vendethiel, the last one is [this](https://github.com/Oire/learnxinyminutes-docs/commit/dc28776a8236381f0209809eb6c7ad61bc5dc223).

**Comment by Oire** [comment]
Sorry guys, I've rebased. Please check that this can be merged now. // cc @vendethiel, @adambard, @levibostian

**Comment by vendethiel** [comment]
amazing :).

**Comment by vendethiel** [comment]
thanks for that!

**Pull request merged**
