### PR TITLE
[c++/es-es] Fix some typos for the C++ article (Spanish)

### PR DESCRIPTION
**Pull request by DiddiLeija**
The Spanish translation has some typos, so I have been fixing them.

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by DiddiLeija** [comment]
I don't know if I should add my name into the file YAML information (maybe as a contributor or a translator?), so please tell me if I have to do something else.

**Comment by DiddiLeija** [comment]
@adambard could you take a look on this?

**Comment by adambard** [comment]
Looks good, thanks! I went ahead and merged so that I don't forget, but if you'd like to add yourself as a either translator or a contributor in a separate PR please feel free. You may have to summon me again to do so though ;)

**Comment by DiddiLeija** [comment]
I was taking a second look into this, and maybe I will post more fixes. Thanks @adambard!

**Pull request merged**
