### PR TITLE
[qsharp]/en] Add documentation for Q#

### PR DESCRIPTION
**Pull request by vivanwin**
- [✓] I solemnly swear that this is all original content of which I am the original author
- [✓] Pull request title is prepended with `[language/lang-code]`
- [✓] Pull request touches only one file (or a set of logically related files with similar changes made)
- [✓] Yes, I have double-checked quotes and field names!

Related to issue: #3115 

Co-authored-by: Mariia Mykhailova <mamykhai@microsoft.com>

### CODE REVIEW

**Comment by AndrewDavis1191** [comment]
This is awesome! Thanks @vivanwin

**Comment by vivanwin** [comment]
Hi,
Great thanks for the merge. Looking at the website, I think there is an error with the rendering on the page.

**Comment by AndrewDavis1191** [comment]
Thanks for pointing that out, I've adjusted the formatting to fix that issue in 7e28066

I think there is a little nuance with the newline before the markdown formatting indicator.

**Comment by kevinnls** [comment]
resolved #3115
close #3115

**Pull request merged**
