### PR TITLE
[bash/es] updated

### PR DESCRIPTION
**Pull request by SerSanGal**
[LearnBash-es.txt](https://github.com/adambard/learnxinyminutes-docs/files/873851/LearnBash-es.txt)
Up date the LearnBash-es.sh

### CODE REVIEW

**Comment by vendethiel** [comment]
Can you please rebase?

**Comment by SerSanGal** [comment]
I'm sorry this is my first PR and I don't know how it works

**Comment by vendethiel** [comment]
I think you forked this repository a long time ago, and so you don't have the latest commits on `master`. When you submitted the PR, github detected a lot of commits were missing.

I'm considering you have two git remotes: `origin` (your repo), and `upstream` (this repo). If you're missing `upstream` (you can check with `git remote`), you can add it with `git remote add upstream https://github.com/adambard/learnxinyminutes-docs.git`.

You can:
1) `git pull` on the upstream repository (this)
2) delete your fork, re-fork, and send a new PR
3) `rebase` your `master` (your remote is `origin`) to this master (the `upstream`).

**Comment by vendethiel** [comment]
I'll close this for now, please tell me if you get back to it.

**Pull request closed without merging**
