### PR TITLE
[bash/en] Add string length & regex code

### PR DESCRIPTION
**Pull request by mn113**
- [✓] I solemnly swear that this is all original content of which I am the original author
- [✓] Pull request title is prepended with `[language/lang-code]`
- [✓] Pull request touches only one file (or a set of logically related files with similar changes made)
- [✓] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [✓] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [✓] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by prertik** [comment]
Merge Conflict! Needs Review.

**Comment by divayprakash** [comment]
@prertik This is ready to be merged now!

**Comment by prertik** [comment]
Sure. Squash and merge @divayprakash!

**Comment by divayprakash** [comment]
@mn113 Thank you for the contribution and welcome to the LXIYM community!

**Pull request merged**
