### PR TITLE
[python/en] removed whitespaces, fixed content extending beyond 80 chars

### PR DESCRIPTION
**Pull request by divayprakash**

### CODE REVIEW

**Comment by divayprakash** [comment]
Why such a long delay in merging, and that too only for formatting changes?

**Comment by divayprakash** [comment]
fixed contributors, please review

**Comment by vendethiel** [comment]
Seems like there are merge conflicts in the file?

**Comment by divayprakash** [comment]
I don't have much experience working with merge conflicts so if you could
guide me on how to proceed that'd be great.
@ven

**Comment by vendethiel** [comment]
Github has some pretty good tutorials: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

(I'll help you if this is not enough to fix it)

**Comment by divayprakash** [comment]
I'll give this a try and see what I can come up with.

**Comment by divayprakash** [comment]
I've tried changing the file reading the Github tutorial but I'm not able to solve this. Maybe another pointer in the right direction? @vendethiel

**Comment by vendethiel** [comment]
The first part is okay (removing markers) is okay. Now you need to pull again from origin (or whatever you called this repo, not yours, on your local git), and fix the new merge conflcits

**Comment by divayprakash** [comment]
I removed the markers, then pulled from origin but didn't get any new merge conflicts

**Comment by vendethiel** [comment]
Well, it seems there are conflicts still. Which remote did you pull from? Your repository; or this one?

**Comment by divayprakash** [comment]
I pulled from my fork

**Comment by vendethiel** [comment]
you need to pull from this repository instead.

**Comment by divayprakash** [comment]
@vendethiel So I need to pull the `master` branch from this repository and rebase my branch `typos-fix4` from `divayprakash/learnxinyminutes-docs` on top of that?

**Comment by divayprakash** [comment]
@vendethiel LGTM, but I confess I'm a newb at this so just check it out.

**Comment by vendethiel** [comment]
I'm not sure what you did, but it seems you added quite a lot of commits.

**Comment by divayprakash** [comment]
How about I just close this PR, close off my development branch `typos-fix4` and start afresh?

**Comment by vendethiel** [comment]
please do :).

**Pull request closed without merging**
