### PR TITLE
RFC: Update julia-es to v0.3.11

### PR DESCRIPTION
**Pull request by Ismael-VC**
- [x] Updated and improved the header.
- [x] Add images.
- [x] Expanded explanation.
- [x] Better formatting (comments).
- [x] Tested with julia `v"0.3.11"`.
- [x] Checked output.

### CODE REVIEW

**Comment by Ismael-VC** [comment]
@adambard bump is there something off in order to merge this?

**Comment by adambard** [comment]
Not really, just hoping for someone who knows spanish and julia better than me to look it over. But, since no such person has come by, thanks!

**Comment by Ismael-VC** [comment]
@adambard thank you very much! I also notified people at [JuliaLangEs](https://gitter.im/JuliaLangEs/julialang-es) about this update in order for them to review this but I didn't recieve any comments.

**Comment by Ismael-VC** [comment]
@adambard this has been merged a while back, but it seems that the website hasn't been updated?

* http://learnxinyminutes.com/docs/es-es/julia-es

Please tell me if I did something wrong or if I still have to do something else, thanks!

**Pull request merged**
