### PR TITLE
[java/en] Added Abstract Classes in Java

### PR DESCRIPTION
**Pull request by bk2dcradle**
Added Abstract Classes in java. Explained how they are different from Interfaces, and a couple or maybe more Caveats. All through code of course.

### CODE REVIEW

**Comment by levibostian** [comment]
Why did you close this @bk2dcradle?

**Comment by vendethiel** [comment]
To reopel another PR

**Comment by bk2dcradle** [comment]
I wanted to squash multiple commits into one to make the one who merges these pull requests easier. I didn't know how to do it, so I closed this pull request and squashed my commits into one, then reopened another. That one has been merged, sorry for the confusion.
Bottom Line: I didn't know how to squash multiple commits into one.

**Comment by levibostian** [comment]
Ok. For future PRs, you don't have to close a pull request. It reflects your branch so you can take your branch, squash the commits, and push the branch up and the PR will, change automatically so you don't have to close and open a new one, just edit the branch. 

You can use [git rebase](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) to squash commits by the way. It's kind of confusing, but once you do it once you will understand it.

**Comment by bk2dcradle** [comment]
Thanks for that. Will remember it next time.

**Pull request closed without merging**
