### PR TITLE
[php/ru] Add magic constants

### PR DESCRIPTION
**Pull request by nasgul**
- [x] PR touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at _intermediate to experienced programmers_ (this is a poor format for explaining fundamental programming concepts)
- [x] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Seriously, look at it now. Watch for quotes and double-check field names.

### CODE REVIEW

**Comment by LanaTim** [comment]
fix conflict and format my changes with contributing rules. sorry, never read instruction at first.

**Comment by vendethiel** [comment]
LGTM. Should I merge now? :)

**Comment by nasgul** [comment]
yes, please. I formated it with rules, and merge with changes.

**Comment by vendethiel** [comment]
Thanks! :cake:

**Pull request merged**
