### PR TITLE
Fix inconsistencies and add resource links

### PR DESCRIPTION
**Pull request by tidupls**

### CODE REVIEW

**Comment by geoffliu** [comment]
@tidupls Could you explain the motivation behind this change? Why move the section up?

Also, please do not add yourself to the contributors list, we do not do that for minor contributions.

**Comment by tidupls** [comment]
Hi Geoff

I moved the section on nesting up to make the order more consistent with
the language feature documentation. I've also seen it discussed earlier in
most tutorials. If you prefer I'll move it back to the original order? I'll
also remove my name from the contributors list. Sorry about that.

**Comment by geoffliu** [comment]
OK I think it's OK to move the section. Please remove yourself from contributor though. Thanks!

**Comment by tidupls** [comment]
Will do. Thanks!

**Comment by geoffliu** [comment]
Thanks!

**Pull request merged**
