### PR TITLE
[LaTeX and λ/lsf] Add a new language

### PR DESCRIPTION
**Pull request by AcProIL**
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Menelion** [comment]
@adambard Can we accept this without separating in two PRs?

**Comment by adambard** [comment]
@Menelion As long as they're both in good shape I have no objection. I noticed that the ISO-639 code for interlingua is `ina` (as opposed to `lsf`), but I'll trust our author @AcProIL with the decision about which is preferred in the community

**Comment by adambard** [comment]
Ah, it seems I was mistaken about which interlingua was involved. I suppose in the absence of an ISO designation `lsf` works as well as anything.

**Comment by AcProIL** [comment]
Yes, another language decided to be called Interlingua after Peano's work, which creates a lot of confusion… We will request an ISO code when the language is active again; probably with the `lsf` code.

**Comment by Menelion** [comment]
@AcProIL Thanks for your contribution! I personally welcome artificial languages, since it's quite unusual to talk about programming in such languages for some reason. Thanks for your work! 👍

**Comment by adambard** [comment]
Who would we programmers be to throw stones at a constructed language :)

**Pull request merged**
