### PR TITLE
[java/en] removed whitespaces, fixed content extending beyond 80 chars

### PR DESCRIPTION
**Pull request by divayprakash**

### CODE REVIEW

**Comment by divayprakash** [comment]
Why such a long delay in merging, and that too only for formatting changes?

**Comment by vendethiel** [comment]
It's taking a long time because I'm trying to answer the oldest ones first, and The backlog haz 200 pull requests in it, so it takes time, sorry.

**Comment by divayprakash** [comment]
Fixed the contributors field ie. removed my name. Kindly review and merge.

**Comment by divayprakash** [comment]
No problem!

**Comment by vendethiel** [comment]
Thanks! :cake:

**Pull request merged**
