### PR TITLE
Chapel: Sync, atomics, reductions, scans, zippered iterators

### PR DESCRIPTION
**Pull request by ian-bertolacci**
Added sync, single and atomic variables.
Added reductions and scans.
Because max/minloc require the values and indices to be in a zippered iterator, I included a demonstration of zippered iterators along with the previous iterator example. 

Further, made a number of spelling, grammar, wording, punctuation changes, and corrected/clarified some erroneous/misleading comments (mainly things about consts and params)

Included the `--set` compiler option in the Notable arguments 'section'.

### CODE REVIEW

**Comment by vendethiel** [comment]
Nice work, thanks! Seems good, except for "zippered", I've never seen that name before. Are chapel's docs using this word?

**Comment by ian-bertolacci** [comment]
Talking with the developers they call such iterations zippered. 
Looking in the texted it can be somewhat varied. 
Section 11.8.1 calls it Zipper Iteration, and 18.4.3 calls it Zippered Iteration.

I think both work in the phrasing zipper(ed) iterators and zipper(ed) iteration.

**Comment by vendethiel** [comment]
would you mind putting `(zipped iterators)` (in parentheses) next to the word? I'll merge it then, thanks :-).

**Comment by ian-bertolacci** [comment]
I like that idea. However I think I misspoke in the text. I dont believe zip() itself is an iterator; not that this changes much.

What I want to say now is:
We can zipper two or more iterators (who have the same number of iterations) together using zip() to create a single zipped iterator, where each iteration of the zipped iterator yields a tuple of the values yielded by one iteration each of the included iterators.

Does this help clear things up? or is more complicated now? 
I think I will also change the example so that the two iterators are quite different and the source of the iteration values could not be confused.

**Comment by vendethiel** [comment]
> yields a tuple of the values yielded by one iteration each of the included iterators.

I think it'd be cleared with "yields a tuple of one value yielded from each iterator" or something like this. That's the only "confusing" part. I'd agree with the remaining one :).

**Comment by ian-bertolacci** [comment]
Agreed. I like that wording better.

**Comment by vendethiel** [comment]
Thanks for your contribution! :cake: :fish_cake:

**Comment by ian-bertolacci** [comment]
No prob! Thanks for including the work!
It makes it easier when I tell people to go learn Chapel if there is actually a place where they could learn Chapel.

**Pull request merged**
