### PR TITLE
[wasm/ua] Add translation

### PR DESCRIPTION
**Pull request by ogroleg**
This pull request adds [wasm/ua] and updates my name in [python/ua]

- (no, translation) I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [x] Yes, I have double-checked quotes and field names!

### CODE REVIEW

**Comment by Menelion** [comment]
@ogroleg Дякую за гарний переклад! Окремий респект за «Ніт!» 👍

**Comment by ogroleg** [comment]
@Menelion перепрошую, там помилка у імені файла, що призводить до кривого білду. Прошу перейменувати wasm.html.markdown -> wasm-ua.html.markdown (або можу кинути ще один пулл)

**Comment by Menelion** [comment]
@ogroleg давайте пул :).

**Comment by ogroleg** [comment]
@Menelion #3681 3681

**Pull request merged**
