### PR TITLE
[pyqt/en] I've done a small example for getting started with the QT framework in python

### PR DESCRIPTION
**Pull request by SirSharpest**
I've added just a small file with (what I feel is enough) for a python intermediate programmer to get started with the QT Framework. 

- All code is tested and works perfectly fine with Python 2.7 and a default installation of the QT libraries. 

- There is room for a few additions such as a brief explanation of installing the framework for python,  and going further into getting I/O from QT objects, as well as signalling and some more advanced features. 

- [x] PR touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Seriously, look at it now. Watch for quotes and double-check field names.

### CODE REVIEW

**Comment by SirSharpest** [comment]
@adambard Was considering beefing this up a little with more in-depth in pyQT but wasn't sure whether to commit time to it or not if the PR isn't suitable.

**Comment by vendethiel** [comment]
I don't see why it wouldn't be :). Tell me when you feel it's ready to merge.

**Comment by SirSharpest** [comment]
I'd think it's okay now as a quick "beginner seeing how easy it is to jump in" example. But I'll be trying over the next week or so to add a lot more. Thanks :)

**Comment by vendethiel** [comment]
Thanks! Feel free to send as many PRs as needed.

**Pull request merged**
