### PR TITLE
[XML/ta] Translated from EN

### PR DESCRIPTION
**Pull request by Kirushanr**
Translated from EN to Tamil

### CODE REVIEW

**Comment by adambard** [comment]
There seems to be a lot more than xml in this PR...

**Comment by vendethiel** [comment]
hi @Kirushanr, there seems to be merge conflicts. This pr also has a few more files than XML still :).

**Comment by Kirushanr** [comment]
Hi @vendethiel ,
I can you you confirm whether the conflicts is resolved now , if i have made any mistake 
i apologize

**Comment by vendethiel** [comment]
Uhmm, not exactly sure what commands you ran, but your history seems garbled now

**Comment by Kirushanr** [comment]
@vendethiel will rebase solve the issue ?

**Comment by vendethiel** [comment]
Rebase should fix it, I'll try to cherry-pick otherwise.

**Comment by vendethiel** [comment]
Going to close this one for now :). Feel free to ping us here if you find some time working on it again! Thanks.

**Pull request closed without merging**
