### PR TITLE
c: use pointer before introduce it.

### PR DESCRIPTION
**Pull request by weakish**
```c
char *s = "ILoveC";
```

Here pointer `*s` is used, but the concept pointer has not been introduced above.

### CODE REVIEW

**Comment by geoffliu** [comment]
Good point, but I do have one concern. You're changing the semantics from pointer assignment to array initialization (which is fine for this example), but we have not introduced array initialization using string literals either. So if we really want to fix this, we should add a line in the initialization section to the effect of

    char s[] = "abc";

is equivalent to

    char s[] = { 'a', 'b', 'c', '\0' };

Also, could you remove the `10`? That is certainly not the correct size, and if you initialize with string literals, the compiler will fill in the correct value for you anyway.

**Comment by vendethiel** [comment]
-1. Let's not confuse people with pointers vs array anymore than they already are.

Also should be `const char *`w

**Comment by geoffliu** [comment]
I was on the fence too, so let's not do this. @vendethiel

**Comment by weakish** [comment]
Thanks @geoffliu, @vendethiel.

Discussing `i++` and `++i` does not need to involve pointer or array.
So I pushed a simplified version with just variable assignment.

**Comment by weakish** [comment]
See #2369

**Pull request closed without merging**
